import type { Section } from "@/lib/types";
const sec: Section = {
  id: "evolution-of-belief",
  num: 9,
  kicker: { en: "Section 09 · The Long Arc", zh: "第九章 · 信仰的长弧" },
  title: { en: "The Evolution of Belief", zh: "信仰进化史" },
  lead: { en: "From the first whispered prayers to animal spirits a hundred thousand years ago to the theological disruptions of the digital age, human belief has never stood still — it adapts, branches, and transforms alongside the civilizations that carry it.", zh: "从十万年前对动物灵魂的第一声低语，到数字时代的神学颠覆，人类的信仰从未停歇——它随着承载它的文明一同适应、分支与蜕变。" },
  body: [
    { en: "Belief is among the oldest technologies our species possesses. Long before writing, agriculture, or cities, anatomically modern humans performed burial rites, painted caves with ochre, and arranged grave goods — evidence that minds were already asking what lies beyond the visible world. This religious impulse appears to be a deep feature of human cognition, not a cultural accident.", zh: "信仰是人类拥有的最古老技术之一。早在文字、农业或城市出现之前，解剖学意义上的现代人类已在举行葬礼仪式、用赭石绘制洞穴壁画、摆放陪葬品——这些证据表明，人类的心智早已在追问可见世界之外存在着什么。这种宗教冲动似乎是人类认知的深层特征，而非文化的偶然。" },
    { en: "The Neolithic Revolution — the shift from hunter-gatherer life to settled agriculture roughly 12,000 years ago — transformed religion alongside everything else. Surplus, hierarchy, and territory gave rise to temple complexes (Göbekli Tepe predates farming itself), professional priests, and pantheons of gods tied to fertility, weather, and kingship. Polytheism flourished in Egypt, Mesopotamia, Greece, Rome, and across South and East Asia, each tradition weaving local ecology and social structure into its cosmology.", zh: "新石器革命——约12,000年前从狩猎采集生活向定居农业的转变——同样彻底改变了宗教。剩余物资、等级制度与领土意识催生了神庙建筑群（哥贝克力石阵甚至早于农业本身）、专职祭司，以及与丰收、气候和王权相连的众神殿堂。多神论在埃及、美索不达米亚、希腊、罗马及南亚、东亚各地蓬勃发展，每个传统都将当地生态与社会结构编织进其宇宙观之中。" },
    { en: "Between roughly 800 and 200 BCE, philosopher-prophets across Eurasia — Confucius, the Buddha, Zoroaster, the Hebrew prophets, Socrates — independently turned inward and questioned the transactional world of sacrifice and appeasement. The German philosopher Karl Jaspers called this window the 'Axial Age': a pivot toward ethics, interiority, and universal principles that still structures much of global thought. The world's major philosophical and salvation religions emerged from or were deeply reshaped by this era.", zh: "约公元前800年至前200年间，欧亚大陆各地的先知与哲学家——孔子、佛陀、琐罗亚斯德、希伯来先知、苏格拉底——不约而同地转向内心，质疑祭祀与安抚神灵的功利性世界。德国哲学家卡尔·雅斯贝尔斯将这一时期称为“轴心时代”：人类思想向伦理、内在性与普世原则的关键转折，其影响至今仍塑造着全球思想的格局。世界主要哲学宗教与救赎宗教，或源于这一时代，或因其而深刻重塑。" },
    { en: "The European Enlightenment of the 17th and 18th centuries introduced secular frameworks — reason, empiricism, natural law — that increasingly competed with religious authority. Industrialisation, Darwinian evolution, and historical biblical criticism further shifted the ground. Yet religion did not retreat uniformly; it diversified. New denominations, new religions, and new spiritualities multiplied alongside secular ideologies, revealing that the human need for meaning, community, and transcendence is remarkably persistent.", zh: "17至18世纪的欧洲启蒙运动引入了世俗框架——理性、经验主义、自然法则——日益与宗教权威展开竞争。工业化、达尔文进化论和历史性圣经批评进一步动摇了宗教的根基。然而宗教并未全面退场，而是走向多元化：新教派、新宗教与新灵性不断涌现，与世俗意识形态并行而生，揭示了人类对意义、共同体与超越性的需求是多么顽强持久。" },
    { en: "The 21st century has introduced a genuinely novel disruption: artificial intelligence, global digital connectivity, and the possibility that non-biological minds might one day be conscious. Some movements already venerate AI as a path to transcendence; others ask whether algorithms can mediate the sacred. Whether AI era belief systems will converge, fragment, or produce something entirely unprecedented remains an open and consequential question for our species.", zh: "21世纪带来了真正前所未有的冲击：人工智能、全球数字互联，以及非生物心智有朝一日或将具备意识的可能性。一些运动已将人工智能奉为通往超越的路径；另一些人则追问算法能否成为神圣的中介。人工智能时代的信仰体系究竟会走向融合、走向碎裂，还是产生全然崭新的形态，对我们这个物种而言仍是一个悬而未决、举足轻重的问题。" },
  ],
  cards: [
    { icon: "🌿", title: { en: "Animism", zh: "泛灵论" }, body: { en: "The oldest stratum of belief: all things — animals, rivers, stones, winds — carry spirit or agency. Hunter-gatherer societies worldwide independently arrived at animistic cosmologies.", zh: "信仰最古老的地层：万物——动物、河流、石头、风——皆有灵魂或意志。全球各地的狩猎采集社会不约而同地发展出泛灵论宇宙观。" } },
    { icon: "🥁", title: { en: "Shamanism", zh: "萨满教" }, body: { en: "Specialist practitioners — shamans — entered altered states to journey between worlds, heal the sick, and negotiate with spirits. Among the most ancient and widespread of religious roles.", zh: "专业实践者——萨满——通过进入变异意识状态在不同世界间穿行，治愈病患，与灵界交涉。这是人类最古老、最普遍的宗教角色之一。" } },
    { icon: "🏛", title: { en: "Polytheism", zh: "多神论" }, body: { en: "Agriculture and cities gave rise to complex pantheons — gods of sun, storm, fertility, war, and death — embedded in temple economies and state ritual. Egypt, Greece, Rome, and Vedic India are canonical examples.", zh: "农业与城市催生了复杂的众神体系——太阳神、风暴神、丰收神、战神与死亡神——嵌入神庙经济与国家礼仪之中。埃及、希腊、罗马与吠陀印度是其中的典范。" } },
    { icon: "☯", title: { en: "Axial Age", zh: "轴心时代" }, body: { en: "800–200 BCE: Confucius, the Buddha, Zoroaster, Hebrew prophets, and Greek philosophers independently shifted religion toward ethics, inner transformation, and universal truths.", zh: "公元前800至前200年：孔子、佛陀、琐罗亚斯德、希伯来先知与希腊哲学家各自独立地将宗教引向伦理、内在转化与普世真理。" } },
    { icon: "✝", title: { en: "Monotheism's Spread", zh: "一神论的传播" }, body: { en: "Judaism, Christianity, and Islam carried the idea of one supreme God across Europe, the Middle East, Africa, and eventually the globe, becoming the dominant religious framework for roughly half of humanity.", zh: "犹太教、基督教与伊斯兰教将唯一至高神的理念传遍欧洲、中东、非洲，最终覆盖全球，成为约半数人类的主流宗教框架。" } },
    { icon: "🔬", title: { en: "Secularism", zh: "世俗主义" }, body: { en: "Enlightenment reason, scientific method, and liberal democracy created public spaces governed by evidence and consent rather than divine authority — though religion remained vital in private life and culture.", zh: "启蒙理性、科学方法与自由民主创造了由证据与共识而非神权主导的公共空间——尽管宗教在私人生活与文化中依然充满活力。" } },
    { icon: "🤖", title: { en: "AI Era", zh: "人工智能时代" }, body: { en: "Digital connectivity and artificial intelligence raise new questions about consciousness, meaning, and the sacred. Algorithmic recommendation shapes religious communities; some movements see AI itself as a path to transcendence.", zh: "数字互联与人工智能带来关于意识、意义与神圣的全新追问。算法推荐塑造着宗教社群；一些运动甚至将人工智能本身视为通往超越的路径。" } },
  ],
  questions: [
    { q: { en: "Is religious belief declining globally, or simply changing form?", zh: "全球宗教信仰是否正在衰退，还是仅仅在改变形式？" }, a: { en: "The picture is mixed. Surveys show declining institutional affiliation in Western Europe, parts of East Asia, and among younger Americans, alongside explosive growth in Sub-Saharan Africa, parts of Southeast Asia, and Pentecostal Christianity worldwide. 'Spiritual but not religious' identities have surged. Belief is diversifying rather than simply vanishing.", zh: "情况颇为复杂。调查显示，西欧、东亚部分地区及美国年轻一代的制度性宗教归属持续下降，而撒哈拉以南非洲、东南亚部分地区以及全球五旬节派基督教则呈现爆炸式增长。“有灵性但不信宗教”的认同大幅上升。信仰正在多元化，而非简单地消亡。" } },
    { q: { en: "Why did the Axial Age produce philosophical revolutions in so many unconnected regions at once?", zh: "为何轴心时代在如此多互不相连的地区同时产生了哲学革命？" }, a: { en: "Scholars debate several factors: rapid urbanisation creating new social complexity, increased long-distance trade bringing ideas into contact, the spread of literacy enabling philosophical texts, and perhaps a shared psychological response to the collapse of older Bronze Age orders. No single cause is accepted, and the synchrony itself remains a compelling puzzle.", zh: "学者们争论多种因素：快速城市化带来的新社会复杂性、远距离贸易的扩大促成思想碰撞、文字传播使哲学文本得以留存，以及也许还有对旧青铜时代秩序崩溃的共同心理回应。目前没有单一原因被普遍接受，而这种同步性本身仍是一个引人深思的谜题。" } },
  ],
  viz: "timeline",
  vizTitle: { en: "8 Eras of Belief", zh: "信仰演化的八个时代" },
  vizData: [
    { label: { en: "Animism", zh: "泛灵论" }, year: -100000, note: { en: "Cave art, burials, and spirit beliefs appear among early Homo sapiens across Africa and Eurasia — the earliest evidence of a religious mind.", zh: "洞穴壁画、葬礼仪式与灵魂信仰在非洲和欧亚大陆的早期智人中出现，是宗教心智最早的证据。" } },
    { label: { en: "Shamanism", zh: "萨满教" }, year: -40000, note: { en: "Specialist spirit-workers — shamans — emerge across Siberia, the Americas, and beyond, using trance and ritual to mediate between human and spirit worlds.", zh: "专业的灵界沟通者——萨满——出现于西伯利亚、美洲及其他地区，借助出神状态与仪式在人类世界与灵界之间斡旋。" } },
    { label: { en: "Polytheism & Agriculture", zh: "多神论与农业" }, year: -10000, note: { en: "Settled farming communities build the first temples (Göbekli Tepe, ~9600 BCE) and develop pantheons tied to agricultural cycles, kingship, and cosmic order.", zh: "定居农耕社区建造了最早的神庙（哥贝克力石阵，约公元前9600年），发展出与农业周期、王权和宇宙秩序相关联的众神体系。" } },
    { label: { en: "Writing & Mythology", zh: "文字与神话" }, note: { en: "The invention of cuneiform and hieroglyphics allows cosmologies to be recorded: the Epic of Gilgamesh, Egyptian Book of the Dead, Vedic hymns.", zh: "楔形文字与象形文字的发明使宇宙观得以记录留存：《吉尔伽美什史诗》、《埃及亡灵书》、吠陀赞美诗由此而来。" }, year: -3000 },
    { label: { en: "Axial Age", zh: "轴心时代" }, year: -500, note: { en: "Confucius, the Buddha, Zoroaster, Hebrew prophets, and Socrates independently redirect religion toward ethics, reason, and inner transformation across Eurasia.", zh: "孔子、佛陀、琐罗亚斯德、希伯来先知与苏格拉底在欧亚大陆各自独立地将宗教引向伦理、理性与内在转化。" } },
    { label: { en: "Spread of Monotheism", zh: "一神论传播" }, year: 100, note: { en: "Christianity spreads across the Roman Empire; later Islam transforms the Middle East, North Africa, Central Asia, and beyond, carrying monotheism to the majority of humanity.", zh: "基督教在罗马帝国内广泛传播；随后伊斯兰教改变了中东、北非、中亚及更广泛地区的面貌，将一神论带给了人类大多数群体。" } },
    { label: { en: "Secularism & Science", zh: "世俗主义与科学" }, year: 1700, note: { en: "The Scientific Revolution, Enlightenment philosophy, and later Darwin's theory of evolution challenge religious authority and establish secular institutions as the basis of modern governance.", zh: "科学革命、启蒙哲学，以及后来的达尔文进化论，挑战了宗教权威，并将世俗机构确立为现代治理的基础。" } },
    { label: { en: "AI & Digital Spirituality", zh: "人工智能与数字灵性" }, year: 2020, note: { en: "Artificial intelligence, virtual reality, and global digital networks open new questions about consciousness, personhood, and the sacred — and spawn new spiritual movements.", zh: "人工智能、虚拟现实与全球数字网络开启了关于意识、人格与神圣性的全新追问，并催生出新的灵性运动。" } },
  ],
  accent: "#e8c074",
};
export default sec;
