import type { Section } from "@/lib/types";
const sec: Section = {
  id: "atheism",
  num: 7,
  kicker: { en: "Section 07 · Without Gods", zh: "第七章 · 无神的世界" },
  title: { en: "Atheism", zh: "无神论" },
  lead: { en: "Atheism is the absence of belief in gods — a position ranging from quiet lack of theistic conviction to an active intellectual and ethical commitment to a world understood entirely without supernatural agency.", zh: "无神论是对神明信仰的缺失——这一立场涵盖从平静地缺乏有神论信念，到在智识和伦理上积极承诺于一个完全无需超自然能动性来理解的世界。" },
  body: [
    { en: "Atheism is defined by negation — the 'a-' prefix simply removes theism — but what fills that space varies enormously. Philosophical atheism can be a minimalist position ('I find no good evidence for gods') or a maximalist one ('the concept of God is incoherent'). It can be cheerfully indifferent to religion or passionately opposed to it. What unites atheists is not a shared positive creed but a shared absence of supernatural belief, which leaves enormous room for diverse metaphysical, ethical, and political positions.", zh: "无神论由否定来定义——前缀「无」仅仅去除了有神论——但由此填充的空间却千差万别。哲学无神论可以是极简主义立场（「我找不到神明存在的良好证据」），也可以是极大主义立场（「神的概念在逻辑上不连贯」）。它可以对宗教愉快地漠不关心，也可以热情地反对它。将无神论者联结在一起的不是共同的积极信条，而是共同缺乏超自然信仰，这为各种形而上学、伦理和政治立场留下了巨大空间。" },
    { en: "Atheism is not a modern Western invention. Ancient Indian Cārvāka philosophy (circa 600 BCE) rejected the Vedas, the soul, and any afterlife, proposing instead a thoroughgoing materialism: 'While life is yours, live joyously; none can escape Death's searching eye.' Ancient Greek atomists Democritus and Epicurus built systems of physics and ethics that required no divine governance. The Chinese philosophical tradition, particularly Confucianism and later Neo-Confucianism, was broadly agnostic or atheistic about personal deities while remaining deeply ethical and cosmologically sophisticated.", zh: "无神论并非现代西方的发明。古印度顺世论哲学（约公元前600年）拒绝承认吠陀、灵魂及任何来世，提出了彻底的唯物主义：「趁有生之年，快乐地生活；没有人能逃脱死亡敏锐的注视。」古希腊原子论者德谟克利特和伊壁鸠鲁建立了不需要神圣治理的物理学和伦理学体系。中国哲学传统，尤其是儒家及后来的新儒家，对位格神明大体持不可知或无神论立场，同时在伦理和宇宙论上保持深刻的精密性。" },
    { en: "The 19th century produced atheism's most influential voices. Ludwig Feuerbach argued that God is a projection of human qualities — 'God is simply the means by which Man recognises his own infinite nature.' Karl Marx developed this into a critique of religion as ideology ('the opium of the people' — a consolation that also functioned as a distraction from material suffering and class oppression). Friedrich Nietzsche's proclamation that 'God is dead' was not a celebration but a diagnosis: European culture had killed its own metaphysical foundation and had not yet faced the consequences.", zh: "19世纪产生了无神论最具影响力的声音。路德维希·费尔巴哈认为神是人类特质的投射——「神不过是人认识自身无限本性的手段」。卡尔·马克思将其发展为对宗教作为意识形态的批判（「人民的鸦片」——一种同时也起到分散对物质苦难和阶级压迫之注意力作用的慰藉）。弗里德里希·尼采宣告「神已死」并非一种庆祝，而是一种诊断：欧洲文化已经杀死了自己的形而上学基础，却尚未面对由此带来的后果。" },
    { en: "Secular humanism is atheism's most developed positive alternative. Rather than anchoring ethics in divine command, secular humanists ground moral reasoning in human flourishing, reason, empathy, and the accumulated insights of moral philosophy. The movement has produced formal statements — the Humanist Manifesto (1933, updated 1973 and 2003) — and institutional networks offering humanist ceremonies for birth, marriage, and death. Prominent humanist thinkers include Bertrand Russell, A. C. Grayling, and the philosopher Philip Kitcher, who argues for 'soft atheism' that respects religious experience while rejecting supernatural belief.", zh: "世俗人文主义是无神论最成熟的积极替代方案。世俗人文主义者不以神圣命令为伦理基础，而是将道德推理植根于人类繁荣、理性、同理心以及道德哲学积累的洞见之中。这一运动产生了正式声明——《人文主义宣言》（1933年，1973年和2003年更新）——以及为出生、婚姻和死亡提供人文主义仪式的机构网络。著名的人文主义思想家包括伯特兰·罗素、A·C·格雷林以及哲学家菲利普·基彻，后者倡导一种尊重宗教经验同时拒绝超自然信仰的「温和无神论」。" },
    { en: "The early 21st century saw the rise of 'New Atheism' — a more confrontational, publicly polemical movement associated with Richard Dawkins (The God Delusion, 2006), Christopher Hitchens (God Is Not Great, 2007), Sam Harris (The End of Faith, 2004), and Daniel Dennett (Breaking the Spell, 2006). The 'Four Horsemen' argued that religious belief is not a private matter but has public consequences — in violence, in educational policy, in resistance to science — and that atheists should say so clearly and loudly. New Atheism attracted fierce criticism not only from religious quarters but also from within secular philosophy, which found its epistemology simplistic and its dismissal of religious experience philosophically naive.", zh: "21世纪初见证了「新无神论」的兴起——一种更具对抗性、公开论战性的运动，与理查德·道金斯（《上帝的错觉》，2006年）、克里斯托弗·希钦斯（《上帝不伟大》，2007年）、萨姆·哈里斯（《信仰的终结》，2004年）以及丹尼尔·丹尼特（《打破魔咒》，2006年）相关联。「四骑士」认为，宗教信仰并非私人事务，而是有公共后果的——在暴力、教育政策以及对科学的抵制方面——无神论者应当清晰而响亮地表明这一立场。新无神论不仅遭到宗教界的激烈批评，也遭到世俗哲学界内部的批评，后者认为其认识论过于简单，对宗教经验的驳斥在哲学上过于天真。" },
  ],
  cards: [
    { icon: "🏛", title: { en: "Secular Humanism", zh: "世俗人文主义" }, body: { en: "An ethical and philosophical stance grounding morality in human reason and flourishing rather than divine command. Offers humanist ceremonies, a naturalistic account of meaning, and engagement with science and democracy as the best tools for human progress.", zh: "一种将道德植根于人类理性与繁荣而非神圣命令的伦理与哲学立场。提供人文主义仪式，对意义给出自然主义解释，并将科学与民主作为人类进步的最佳工具。" } },
    { icon: "⚛", title: { en: "Philosophical Materialism", zh: "哲学唯物主义" }, body: { en: "The position that only physical matter and energy exist, and that consciousness, meaning, and value are emergent from physical processes — not from any immaterial soul or divine realm. Traced from Democritus through Marx and Feuerbach to contemporary physicalism.", zh: "一种认为只有物质和能量存在的立场，意识、意义与价值均由物理过程涌现，而非来自任何非物质灵魂或神圣领域。从德谟克利特经马克思和费尔巴哈延伸至当代物理主义。" } },
    { icon: "🔭", title: { en: "Scientific Worldview", zh: "科学世界观" }, body: { en: "Many atheists root their worldview in science: a cosmos of 13.8 billion years, governed by natural laws, where life arose by evolution and consciousness by neural complexity — awe-inspiring without requiring supernatural authorship.", zh: "许多无神论者将世界观植根于科学：一个138亿年历史的宇宙，由自然规律支配，生命通过进化而生，意识由神经复杂性而来——令人敬畏，无需超自然的创作者。" } },
    { icon: "🧠", title: { en: "Rationalism & Freethought", zh: "理性主义与自由思想" }, body: { en: "The 18th-century Enlightenment produced freethinking philosophers (Voltaire, Hume, d'Holbach) who applied reason and skepticism to religious claims. The freethought tradition prized intellectual autonomy and the rejection of authority unjustified by evidence.", zh: "18世纪的启蒙运动产生了自由思想的哲学家（伏尔泰、休谟、霍尔巴赫），他们将理性和怀疑主义应用于宗教主张。自由思想传统珍视智识自主性以及对证据不支持的权威的拒绝。" } },
    { icon: "✍", title: { en: "New Atheism", zh: "新无神论" }, body: { en: "The early 21st-century movement of Dawkins, Hitchens, Harris, and Dennett argued that religion is harmful to individuals and society and that atheists should say so publicly. Influential as cultural critique; criticized within philosophy for reductionism and caricature of religion.", zh: "道金斯、希钦斯、哈里斯和丹尼特21世纪初的运动认为宗教对个人和社会有害，无神论者应公开表明这一立场。作为文化批评具有影响力；在哲学界因简化主义和对宗教的漫画式描绘而受到批评。" } },
    { icon: "🌐", title: { en: "Buddhist Atheism", zh: "佛教无神论" }, body: { en: "Early Buddhism makes no claim about a creator god and the Buddha explicitly declined to answer metaphysical questions about God's existence. Many contemporary Buddhists and Buddhist-inspired practitioners consider themselves atheist — ethics, mindfulness, and liberation without theism.", zh: "早期佛教不对造物主提出任何主张，佛陀明确拒绝回答关于神明存在的形而上学问题。许多当代佛教徒和受佛教启发的修行者认为自己是无神论者——无需有神论的伦理、正念与解脱。" } },
    { icon: "♻", title: { en: "Existential Naturalism", zh: "存在主义自然主义" }, body: { en: "Philosophers like Albert Camus and Jean-Paul Sartre confronted the 'absurd' — the gap between human desire for meaning and the universe's silence — without retreating to religion. Sartre's 'existence precedes essence' places the burden and freedom of meaning-making squarely on human choice.", zh: "阿尔贝·加缪和让-保罗·萨特等哲学家直面「荒诞」——人类对意义的渴望与宇宙的沉默之间的鸿沟——而不退回到宗教。萨特的「存在先于本质」将意义建构的负担和自由完全置于人类选择之上。" } },
  ],
  questions: [
    { q: { en: "Is atheism itself a belief system or merely an absence of one?", zh: "无神论本身是一种信仰体系，还是仅仅是信仰的缺失？" }, a: { en: "Strictly speaking, atheism is only the absence of theistic belief — like 'non-stamp-collecting' is not itself a hobby. But in practice many atheists hold rich positive commitments: to science, reason, human rights, and naturalistic ethics. These positive commitments constitute a worldview, even if 'atheism' names only one of its features — the absence of god-belief.", zh: "严格来说，无神论仅仅是缺乏有神论信仰——就像「不集邮」本身不是一种爱好。但在实践中，许多无神论者持有丰富的积极承诺：对科学、理性、人权和自然主义伦理的承诺。这些积极承诺构成了一种世界观，即使「无神论」只命名了其特征之一——缺乏对神明的信仰。" } },
    { q: { en: "Can atheists have a meaningful relationship with death, ritual, and transcendence?", zh: "无神论者能够与死亡、仪式和超越性建立有意义的关系吗？" }, a: { en: "Many atheists argue yes — and humanist ceremonies for birth, marriage, and death demonstrate this in practice. Transcendence can be reinterpreted as the experience of awe before the cosmos, deep human connection, aesthetic absorption, or the continuity of influence after death. Whether this is sufficient, or whether it leaves an irreplaceable gap, is one of the most genuinely contested questions in secular philosophy.", zh: "许多无神论者认为可以——人文主义的出生、婚姻和死亡仪式在实践中证明了这一点。超越性可以被重新诠释为面对宇宙的敬畏体验、深刻的人际联结、审美沉浸或死后影响力的延续。这是否足够，或者是否留下了不可替代的空缺，是世俗哲学中最真实争议的问题之一。" } },
  ],
  viz: "cards",
  vizTitle: { en: "Schools of Atheist Thought", zh: "无神论思想流派" },
  accent: "#74b6e6",
};
export default sec;
