import type { Section } from "@/lib/types";
const sec: Section = {
  id: "animism",
  num: 6,
  kicker: { en: "Section 06 · The Living World", zh: "第六章 · 有灵的世界" },
  title: { en: "Animism", zh: "泛灵论" },
  lead: { en: "Animism is the world's oldest and most widely distributed spiritual orientation: the recognition that persons, agency, and spirit extend far beyond the human body into animals, plants, rivers, mountains, and the dead.", zh: "泛灵论是世界上最古老、分布最广的精神取向：认识到人格、能动性与灵性远超人类躯体，延伸至动物、植物、河流、山岳与亡者之中。" },
  body: [
    { en: "The term 'animism' was introduced by the anthropologist Edward Tylor in his 1871 work Primitive Culture, where he proposed it as the earliest form of religion — a 'belief in spiritual beings'. Though Tylor's evolutionary framing (animism as primitive precursor to higher religion) has been thoroughly rejected by contemporary scholarship, the phenomenon he identified is real and global: indigenous peoples across every continent have articulated relational ontologies in which the world teems with minded, intentional, communicating presences.", zh: "「泛灵论」一词由人类学家爱德华·泰勒在其1871年著作《原始文化》中提出，他将其定位为宗教的最早形式——「对灵性存在的信仰」。尽管泰勒的进化论框架（将泛灵论视为高等宗教的原始前驱）已被当代学术界彻底否定，但他所识别的现象是真实而全球性的：各大洲的原住民都阐述了关系性本体论，在其中世界充满了具有心智、意图和沟通能力的临在。" },
    { en: "Modern anthropologist Graham Harvey defines animism not as a belief system but as a relational practice: 'animists are people who recognize that the world is full of persons, only some of whom are human, and that life is always lived in relationship with others.' On this view, animism is less about metaphysical doctrine and more about an ethical orientation — how one relates to the deer, the oak, the river, the ancestor — that demands respectful negotiation rather than simple exploitation.", zh: "现代人类学家格雷厄姆·哈维将泛灵论定义为一种关系性实践，而非信仰体系：「泛灵论者是那些认识到世界充满了人格存在的人，其中只有一部分是人类，而生命始终是在与他者的关系中度过的。」在这一视角下，泛灵论与其说是形而上学教义，不如说是一种伦理取向——如何与鹿、橡树、河流、祖先相处——这要求尊重的协商而非单纯的开采。" },
    { en: "Nature spirits are among the most widespread animistic presences. Many Siberian and Central Asian traditions speak of the spirits of mountains, winds, and waters that must be propitiated before a hunt or journey. Japanese Shinto recognizes kami — sacred presences — dwelling in mountains (Fujisan), waterfalls, ancient trees, and household objects. West African Yoruba traditions identify orishas associated with rivers (Oshun), iron and roads (Ogun), and the sea (Yemoja). The specificity of these relationships — this river, this grove, this threshold — distinguishes animistic ecology from abstract nature-worship.", zh: "自然精灵是最普遍的泛灵论临在之一。许多西伯利亚和中亚传统谈到山岳、风与水之灵，在狩猎或旅行前必须加以安抚。日本神道教认识到神明（kami）——神圣临在——栖居于山岳（富士山）、瀑布、古木和家庭器物之中。西非约鲁巴传统将奥里沙与河流（奥顺）、铁和道路（奥贡）及大海（耶莫加）相联系。这些关系的具体性——这条河、这片树林、这道门槛——将泛灵论生态观与抽象的自然崇拜区分开来。" },
    { en: "Ancestor spirits form a second great axis. Across sub-Saharan Africa, East Asia, Mesoamerica, and Pacific Island cultures, the dead do not simply vanish — they become a category of powerful, interested persons who watch over their descendants, communicate through dreams and divination, and require ritual feeding, remembrance, and respect. In Chinese tradition, ancestral tablets on the family altar anchor a living relationship between generations. In Andean Quechua communities, the mallquis (mummified ancestors) were consulted and carried in procession as recently as the colonial period.", zh: "祖先之灵构成第二条重要轴线。在撒哈拉以南非洲、东亚、中美洲和太平洋岛屿文化中，死者并非简单地消失——他们成为一类有力量、有关切的人格存在，守护着后代，通过梦境和占卜进行沟通，并需要仪式性的供奉、追忆与尊重。在中国传统中，家族祠堂上的祖先牌位是代际间活态关系的锚点。在安第斯克丘亚社区，祖先木乃伊（mallquis）直至殖民时期仍被用于咨询并抬出游行。" },
    { en: "Animism is not a relic of the past. Ethnographic surveys suggest that animistic attitudes persist inside and alongside formally monotheistic or secular societies — the belief in ghosts, in the personality of places, in the significance of animal encounters, in a living quality of certain objects. Scholars of religion increasingly see animism not as a primitive stage to be transcended but as a perennial human responsiveness to the perceived aliveness of the world — one that resurfaces in ecological thinking, deep ecology, and new materialist philosophy.", zh: "泛灵论并非过去的遗迹。民族志调查表明，泛灵论态度在正式的一神论或世俗社会内部及其旁边持续存在——对鬼魂的信仰、对地方个性的感知、对动物相遇之意义的理解、对某些物品活态特质的感受。宗教学者越来越将泛灵论视为一种永恒的人类对世界所感知到的生命力的回应——而非有待超越的原始阶段——它在生态思想、深层生态学和新唯物主义哲学中不断重现。" },
  ],
  cards: [
    { icon: "🌿", title: { en: "Nature Spirits", zh: "自然精灵" }, body: { en: "Mountains, rivers, winds, and forests are inhabited by distinct spiritual presences in traditions from Siberia to Japan to West Africa. These spirits have personalities, preferences, and must be addressed with respect.", zh: "从西伯利亚到日本再到西非，山岳、河流、风与森林中栖居着各具特色的灵性临在。这些精灵有其个性与偏好，必须以尊敬的态度与之交流。" } },
    { icon: "🦅", title: { en: "Animal Spirits", zh: "动物精灵" }, body: { en: "Animals are kin, teachers, or spiritual guardians in many indigenous traditions. Totemic relationships (bear clans, eagle societies) encode moral obligations; shamans communicate with animal helpers across the spirit world.", zh: "在许多原住民传统中，动物是亲属、导师或灵性守护者。图腾关系（熊氏族、鹰会社）编码着道德义务；萨满在灵界与动物助手沟通。" } },
    { icon: "🕯", title: { en: "Ancestor Spirits", zh: "祖先之灵" }, body: { en: "The dead become interested persons who watch over the living, communicate through dreams and divination, and require periodic ritual nourishment. Chinese ancestor veneration, Yoruba egungun masquerades, and Día de Muertos all enact this relationship.", zh: "亡者成为关注生者的人格存在，通过梦境与占卜进行沟通，并需要定期仪式性的供奉。中国祭祖、约鲁巴面具舞以及亡灵节都在践行这一关系。" } },
    { icon: "🏔", title: { en: "Place Spirits", zh: "地方精灵" }, body: { en: "Specific locations — a particular tree, spring, crossroads, or mountain — concentrate spiritual power. Roman lares and genius loci, Andean apus (mountain spirits), and Japanese shrine-bound kami all reflect this geography of the sacred.", zh: "特定地点——某棵树、泉眼、十字路口或山岳——汇聚着灵性力量。罗马的拉瑞斯与地方守护灵、安第斯的阿普斯（山灵）以及日本神社所系之神明，都体现了这种神圣的地理学。" } },
    { icon: "🌀", title: { en: "Shamanic Mediation", zh: "萨满中介" }, body: { en: "Specialist practitioners (shamans, sangoma, curanderos) navigate between the human and spirit worlds, diagnosing illness, negotiating with offended spirits, and retrieving lost souls. The shaman's role is relational rather than priestly.", zh: "专职修行者（萨满、桑戈玛、萨满师）在人类世界与灵界之间穿行，诊断疾病，与被冒犯的精灵协商，找回失落的灵魂。萨满的角色是关系性的，而非祭司性的。" } },
    { icon: "🪶", title: { en: "New Animism", zh: "新泛灵论" }, body: { en: "Graham Harvey and others frame animism as an ethical relational practice rather than a primitive belief. Deep ecology, indigenous rights movements, and legal personhood for rivers (New Zealand's Whanganui) reflect animistic sensibilities in modern contexts.", zh: "格雷厄姆·哈维等学者将泛灵论定义为伦理关系实践，而非原始信仰。深层生态学、原住民权利运动以及赋予河流法律人格（新西兰旺阿努伊河）在现代语境中体现了泛灵论的感知方式。" } },
  ],
  questions: [
    { q: { en: "Is animism compatible with scientific naturalism?", zh: "泛灵论与科学自然主义相容吗？" }, a: { en: "Some philosophers argue that animism as a relational ethic — treating other entities as worthy of moral consideration — is compatible with and even enriched by ecology and cognitive science, which show that plants signal, fungi communicate, and animals have rich inner lives. The metaphysical claim that there are literally separate spiritual entities is a different question that science neither confirms nor fully refutes.", zh: "一些哲学家认为，作为关系伦理的泛灵论——将其他实体视为值得道德关注的存在——与生态学和认知科学相容，甚至因后者而得以丰富；这些科学表明植物会发出信号、真菌能够沟通、动物有丰富的内心生活。关于是否确实存在独立灵性实体的形而上学主张是另一个问题，科学既未确认也未完全否定。" } },
  ],
  viz: "constellation",
  vizTitle: { en: "Spirit-World Map", zh: "灵界地图" },
  vizData: [
    { label: { en: "Mountain Spirit", zh: "山灵" }, group: "Nature Spirits", note: { en: "Venerated across Siberian, Andean (apu), and Shinto traditions as powerful territorial presences.", zh: "西伯利亚、安第斯（阿普斯）及神道传统均崇敬山灵，视其为强大的地域临在。" } },
    { label: { en: "River Spirit", zh: "河灵" }, group: "Nature Spirits", note: { en: "Oshun (Yoruba), Ganga Ma (Hindu), and the legally recognised Whanganui (Māori) are named river persons.", zh: "奥顺（约鲁巴）、恒河女神（印度教）以及获法律认可的旺阿努伊河（毛利）均为具名河灵。" } },
    { label: { en: "Tree & Forest Spirit", zh: "树木与森林精灵" }, group: "Nature Spirits", note: { en: "Ancient trees hold kami in Shinto; dryads in Greek myth; forest spirits guide hunters in many Amazonian traditions.", zh: "神道教认为古树栖居神明；希腊神话中有树精；亚马逊众多传统中森林精灵引导猎人。" } },
    { label: { en: "Wind & Sky Spirit", zh: "风与天空之灵" }, group: "Nature Spirits", note: { en: "Lakota Wakan Tanka, Mongolian Tengri, and many other sky-spirit traditions animate atmospheric forces with personhood.", zh: "拉科塔族的瓦坎唐卡、蒙古的腾格里以及许多其他天空灵性传统赋予大气力量以人格。" } },
    { label: { en: "Totem Animal", zh: "图腾动物" }, group: "Animal Spirits", note: { en: "Clan totems (bear, eagle, raven) in North American First Nations define social groups and moral obligations toward kin species.", zh: "北美原住民的氏族图腾（熊、鹰、渡鸦）界定社会群体及对亲缘物种的道德义务。" } },
    { label: { en: "Animal Helper", zh: "动物助灵" }, group: "Animal Spirits", note: { en: "Shamans across Siberia and the Americas cultivate personal animal spirit helpers who accompany and guide them in the spirit world.", zh: "西伯利亚和美洲的萨满培育个人动物助灵，它们在灵界陪伴并引导萨满。" } },
    { label: { en: "Jaguar Spirit (Amazonia)", zh: "美洲虎之灵（亚马逊）" }, group: "Animal Spirits", note: { en: "For many Amazonian peoples the jaguar is a master of the spirit world; shamans transform into jaguars during ritual trance.", zh: "对许多亚马逊人而言，美洲虎是灵界的主宰；萨满在仪式性出神期间变身为美洲虎。" } },
    { label: { en: "Household Ancestors", zh: "家宅祖灵" }, group: "Ancestor Spirits", note: { en: "Venerated at domestic altars (Chinese ancestral tablets, Roman lares) — the dead remain active members of the family household.", zh: "在家宅神龛（中国祖先牌位、罗马拉瑞斯）受到供奉——亡者仍是家庭的活跃成员。" } },
    { label: { en: "Founding Ancestor", zh: "始祖之灵" }, group: "Ancestor Spirits", note: { en: "Legendary founders (Nurhaci for Manchu, Amaterasu's lineage for Japanese imperial house) become potent ancestral presences shaping community identity.", zh: "传说中的祖先（满族的努尔哈赤、日本皇室的天照大神谱系）成为塑造社群认同的强大祖灵临在。" } },
    { label: { en: "Egungun Masquerade (Yoruba)", zh: "埃贡贡面具舞（约鲁巴）" }, group: "Ancestor Spirits", note: { en: "Masked dancers embody returning ancestors who come to adjudicate disputes, bless the community, and communicate messages from the dead.", zh: "带面具的舞者化身归来的祖先，前来裁决纠纷、祝福社区并传递亡者的信息。" } },
    { label: { en: "Genius Loci (Place Spirit)", zh: "地方守护灵" }, group: "Place Spirits", note: { en: "Roman genius loci — the spirit of a particular place — extended later into medieval Christian holy wells and Shinto shrine boundaries.", zh: "罗马的地方守护灵概念后来延伸至中世纪基督教圣泉和神道神社结界。" } },
    { label: { en: "Apu Mountain Lord (Andes)", zh: "阿普斯山神（安第斯）" }, group: "Place Spirits", note: { en: "Andean apus are sentient mountain lords who control weather, fertility, and the fate of communities living in their shadow.", zh: "安第斯的阿普斯是有意识的山神，掌控气候、丰饶以及生活在其庇护下的社区命运。" } },
  ],
  accent: "#7fe0a8",
};
export default sec;
