import type { Section } from "@/lib/types";
const sec: Section = {
  id: "taoism",
  num: 11,
  kicker: { en: "Section 11 · The Way", zh: "第十一章 · 道" },
  title: { en: "Taoism", zh: "道家与道教" },
  lead: { en: "Taoism is a family of Chinese philosophical, religious, and mystical traditions united by the concept of the Tao — the unnameable ground of all existence, the ceaseless flow that underlies nature, society, and the self — and by the practical arts of aligning with it.", zh: "道家与道教是一族中国哲学、宗教与神秘主义传统的总称，以「道」为共同核心——那不可名状的万有根基、贯穿自然、社会与自我的永恒流动——以及与之相契合的实践之道。" },
  body: [
    { en: "The word Tao (道) is usually translated as 'the Way', but its meaning resists reduction. The first line of the foundational text, the Tao Te Ching, declares: 'The Tao that can be named is not the eternal Tao.' Tao is the source from which all things arise, the pattern that permeates all things, and the process by which all things return. It is not a creator god, not a personal being, and not a law imposed on nature — it is more like the nature of nature itself, what things do when left to their own spontaneous unfolding.", zh: "「道」字通常被译为「the Way」，但其含义难以简化。奠基性文本《道德经》的第一句话便宣告：「道可道，非常道。」道是万物由之生发的本源，是贯穿一切的内在秩序，也是万物归复的运动过程。它不是创世神，不是具有位格的存在，也不是强加于自然的律法——它更像是自然的本性本身，是万物在任其自然展开时所呈现的状态。" },
    { en: "The Tao Te Ching, attributed to the sage Laozi (Lao-tzu) and likely compiled in the 4th–3rd century BCE, is one of the most translated books in history. Its 81 brief, paradoxical chapters commend the virtues of softness over hardness, emptiness over fullness, yielding over force, and unknowing over cleverness. The Zhuangzi, attributed to the philosopher Zhuangzi (c. 369–286 BCE), extends these themes with elaborate parables, dream-logic, and a celebration of radical freedom from social convention and the fixities of language.", zh: "《道德经》相传为圣人老子所著，大约成书于公元前4至3世纪，是历史上被翻译次数最多的书籍之一。其81章简短而充满悖论的文字，推崇柔弱胜刚强、虚空胜盈满、顺势胜强力、守拙胜聪明的德行。《庄子》相传为哲学家庄子（约公元前369—前286年）所著，以繁复的寓言、梦境逻辑与对彻底自由于社会惯习及语言固执之外的礼赞，将这些主题进一步深化。" },
    { en: "Wu Wei (無為), often translated as 'non-action' or 'effortless action', is perhaps the most practically oriented Taoist concept. It does not mean passivity or inaction, but action so perfectly attuned to circumstances that it requires no forcing, no struggle, no expenditure of unnecessary effort — like water finding its path downhill, or a skilled craftsman whose hand moves without deliberate thought. Wu Wei is the art of acting in accordance with the natural grain of things.", zh: "无为（無為）常被译为「non-action」或「effortless action」，是最具实践导向的道家概念。它并不意味着消极或无所作为，而是指一种与情境完美契合的行动——无需强制、无需挣扎、无需消耗多余气力——如水自然寻路而下，如技艺娴熟的工匠手随心动而无需刻意思量。无为是依循万物自然纹理而行的艺术。" },
    { en: "Taoism also developed as an organized religion (Daojiao) distinct from the philosophical school (Daojia). From the 2nd century CE onward, religious Taoism organized priestly lineages, built temples, compiled vast scriptural canons, developed complex liturgy, and incorporated local Chinese deities, immortals, and folk practices into a living institutional tradition. The pursuit of physical immortality (xian) through internal alchemy (neidan) — breathing exercises, meditation, dietary arts, and the cultivation of qi — became a central religious aspiration. This tradition produced both the meditative arts absorbed into later Chinese Buddhism and precursors to Chinese medicine.", zh: "道教也发展为一种有组织的宗教（道教），有别于哲学流派（道家）。自公元2世纪起，道教组织起祭司传承，兴建宫观，编纂浩繁的道藏，发展复杂的科仪，并将中国本土神灵、仙真与民间信仰纳入活态的制度性传统之中。通过内丹修炼——导引吐纳、静坐冥思、饮食调养与培育真气——追求肉身成仙（仙）成为核心宗教志向。这一传统既孕育了后来被中国佛教所吸收的禅定之道，也造就了中医学的先驱。" },
    { en: "Taoism has shaped Chinese civilization so pervasively that it can be difficult to isolate its influence — it infuses Chinese aesthetics (landscape painting, poetry, calligraphy), medicine, martial arts (Tai Chi, Qigong), culinary culture, and the very grammar of how Chinese people think about change, balance, and the natural world. In the 20th and 21st centuries, Taoist ideas have found wide resonance in the West: in ecology, systems thinking, psychotherapy, and popular culture, where 'go with the flow' and 'yin and yang' have entered everyday speech.", zh: "道家与道教对中华文明的塑造如此深远，以至于难以单独剥离其影响——它渗入中国美学（山水画、诗歌、书法）、医学、武术（太极、气功）、饮食文化，乃至中国人思考变化、平衡与自然世界的思维方式本身。20至21世纪，道家思想在西方获得广泛共鸣：在生态学、系统思维、心理治疗与流行文化中，「顺其自然」与「阴阳」已进入日常话语。" },
  ],
  cards: [
    { icon: "∞", title: { en: "Tao (道)", zh: "道" }, body: { en: "The unnameable source, pattern, and process of all existence. Not a god, not a law, not a place — the Tao is what things are when left to unfold naturally. It precedes heaven and earth, yet is present in every leaf, stone, and breath.", zh: "万有的不可名状之本源、内在秩序与运动过程。不是神，不是律法，不是场所——道是万物在任其自然展开时所呈现的本相。它先于天地而存在，却又在每一片叶、每一块石、每一次呼吸之中在场。" } },
    { icon: "🌊", title: { en: "Wu Wei (無為)", zh: "无为" }, body: { en: "Effortless action: moving with the grain of reality rather than against it. The sage acts without forcing, achieves without striving, and influences without dominating — like water, which overcomes stone not by force but by persistent yielding.", zh: "无力之力：顺应现实的纹理而动，而非逆之而行。圣人行事无强制，成就无争竞，影响而不主宰——如水，克石非凭力，而凭持久的柔顺。" } },
    { icon: "☯", title: { en: "Yin-Yang (陰陽)", zh: "阴阳" }, body: { en: "The twin poles of existence — dark and light, receptive and assertive, yielding and firm, feminine and masculine — are not opposites that exclude each other but complementary aspects of a single dynamic whole. Each contains the seed of the other; each gives rise to the other.", zh: "存在的两极——暗与明、容受与主动、柔顺与刚强、阴柔与阳刚——并非相互排斥的对立，而是一个动态整体的互补面向。每一极都包含另一极的种子；每一极都孕育另一极的生成。" } },
    { icon: "📖", title: { en: "Tao Te Ching (道德經)", zh: "道德经" }, body: { en: "Eighty-one short, paradoxical chapters attributed to the sage Laozi, composed around the 4th–3rd century BCE. One of the most translated books in human history, it lays out the vision of governing, living, and being in accord with the Tao through softness, emptiness, and non-contention.", zh: "81章简短而充满悖论的文字，相传为圣人老子所著，约成书于公元前4至3世纪。它是人类历史上被翻译次数最多的书籍之一，以柔弱、虚空与不争为纲，阐述顺应大道的治国、处世与存在之道。" } },
    { icon: "🦋", title: { en: "Zhuangzi (莊子)", zh: "庄子" }, body: { en: "The philosopher Zhuangzi (c. 369–286 BCE) expanded Taoist philosophy through vivid parables — the butterfly dream, Cook Ding carving the ox, the giant fish Kun becoming a bird — celebrating perspectivism, radical freedom, and the relativity of all human distinctions.", zh: "哲学家庄子（约公元前369—前286年）以生动的寓言——蝴蝶梦、庖丁解牛、鲲化为鹏——拓展了道家哲学，礼赞视角主义、彻底自由与人类一切区分的相对性。" } },
    { icon: "⚗", title: { en: "Immortality & Neidan (內丹)", zh: "成仙与内丹" }, body: { en: "Religious Taoism developed elaborate practices aimed at achieving physical immortality or spiritual transcendence: internal alchemy (neidan) cultivating jing (essence), qi (vital breath), and shen (spirit) through meditation, breathwork, dietary regulation, and visualisation. Many of these techniques overlap with Chinese medicine and influenced the development of acupuncture and herbal traditions.", zh: "道教发展出精细复杂的修炼体系，旨在实现肉身成仙或精神超越：内丹之道通过静坐冥思、导引吐纳、饮食调节与内视观想，修炼精、气、神。许多技术与中医相互交融，并影响了针灸与本草传统的发展。" } },
  ],
  questions: [
    { q: { en: "Is Taoism a philosophy or a religion — and does the distinction matter?", zh: "道家是哲学还是宗教——这种区分重要吗？" }, a: { en: "Western scholarship long distinguished sharply between 'philosophical Taoism' (Daojia, the Laozi/Zhuangzi texts) and 'religious Taoism' (Daojiao, the organized church traditions). Many Chinese and contemporary scholars argue this is a false dichotomy imposed by Western categories: the texts and the ritual traditions grew from the same root and have always interpenetrated. The Tao Te Ching was used liturgically; religious Taoism engaged seriously with philosophical questions about nature and transformation.", zh: "西方学术界长期以来将「道家哲学」（道家，即老子/庄子的文本传统）与「道教」（道教，即有组织的教会传统）严格区分。但许多中国学者和当代学者认为，这是一种西方范畴强加的虚假二分：文本传统与仪式传统根出一处，始终相互渗透。《道德经》曾被用于科仪礼拜；道教也认真探讨关于自然与转化的哲学问题。" } },
    { q: { en: "What does Taoism offer to contemporary ecological thinking?", zh: "道家思想能为当代生态思想提供什么？" }, a: { en: "Taoist naturalism — the idea that humans flourish by aligning with natural patterns rather than dominating them — resonates strongly with ecological ethics. Concepts like wu wei, the interdependence of yin and yang, and the rejection of anthropocentrism have been drawn upon by deep ecology, environmental philosophy, and sustainable design movements. Some scholars argue that Taoist cosmology, which lacks a doctrine of human exceptionalism or divine mandate to subdue nature, provides philosophical resources that Western nature-religions and secular environmentalism lack.", zh: "道家自然主义——人类通过契合自然秩序而非主宰自然而蓬勃生长的理念——与生态伦理学高度共鸣。无为、阴阳相互依存，以及拒绝人类中心主义等概念，已被深层生态学、环境哲学与可持续设计运动所借鉴。一些学者认为，道家宇宙观缺乏人类例外主义或神命主宰自然的教义，为西方自然宗教与世俗环保主义所欠缺的哲学资源提供了补充。" } },
  ],
  viz: "cards",
  accent: "#5fd6c4",
};
export default sec;
