import type { Section } from "@/lib/types";
const sec: Section = {
  id: "witchcraft",
  num: 17,
  accent: "#a489ff",
  kicker: { en: "Section 17 · Magic & Power", zh: "第十七章 · 魔法与力量" },
  title: { en: "Witchcraft & Magical Traditions", zh: "巫术与魔法传统" },
  lead: { en: "Across every continent, people have understood that certain individuals could bend the forces of nature, speak to spirits, and reshape destiny — practices celebrated as wisdom in some eras and condemned as heresy in others.", zh: "在每一片大陆上，人们都相信某些个体能够驾驭自然之力、与灵界沟通、改写命运——这些实践在某些时代被奉为智慧，在另一些时代却被打为异端。" },
  body: [
    { en: "Folk magic traditions are among the oldest and most widespread forms of human spiritual practice. Herbalism, divination, protective charms, and healing rituals appear in virtually every pre-industrial culture — from the cunning-folk of rural England who sold love charms and located lost cattle, to the curanderas of Mesoamerica who combined plant medicine with Catholic prayer, to the griots of West Africa who preserved communal memory and interceded with ancestors. These practitioners occupied a liminal social role: respected when their magic succeeded, blamed when it failed.", zh: "民间魔法传统是人类最古老、最普遍的精神实践形式之一。草药学、占卜、护身符和治愈仪式几乎出现在每一个前工业社会——从英格兰农村出售爱情咒符、寻找走失牲畜的「聪明人」，到将植物医学与天主教祷告融为一体的中美洲萨满医者，再到保存社区记忆并向祖先祈求庇护的西非吟游诗人。这些实践者占据着一种边缘性的社会角色：当魔法奏效时受到尊崇，当魔法失败时遭到责难。" },
    { en: "The early modern witch-hunts of Europe (roughly 1450–1750) represent one of history's most devastating episodes of state-sponsored persecution. Approximately 40,000–60,000 people were executed, the majority of them women, following accusations of diabolical compact, maleficium (harmful magic), and heresy. The hunts were driven by a confluence of factors: the theological elaboration of Satanism in texts like the Malleus Maleficarum (1487), social scapegoating during famines and plagues, inquisitorial legal procedures that relied on torture, and community disputes in which long-standing resentments crystallized into accusations. The Salem trials of 1692 in colonial Massachusetts are among the best-documented American examples. Historians today read the witch-hunts as a lens onto gender, power, and theological anxiety — not as evidence of actual magical practice.", zh: "欧洲近代早期的猎巫运动（约1450至1750年）是历史上最具破坏性的国家迫害事件之一。约有四至六万人被处决，其中大多数是女性，罪名为与魔鬼订立契约、施行恶法和异端邪说。猎巫运动由多重因素共同推动：《女巫之锤》（1487年）等文本对撒旦主义的神学建构、饥荒与瘟疫期间的社会替罪羊机制、依赖酷刑的宗教裁判所法律程序，以及社区内部长期积怨最终演变为指控的过程。1692年殖民地马萨诸塞州的塞勒姆审判是美国最有据可查的案例之一。历史学家今天将猎巫运动视为审视性别、权力与神学焦虑的棱镜，而非实际魔法活动的证据。" },
    { en: "Outside Europe, indigenous magical practices have had complex relationships with colonialism. In the Americas, Africa, and Asia, colonial authorities and missionaries frequently criminalized local healing traditions, divination systems, and spirit-mediumship — labeling them witchcraft in order to delegitimize entire worldviews. The Vodou of Haiti, the Candomblé of Brazil, and the Santería of Cuba all survived by creatively blending African spiritual practice with Catholic iconography, creating syncretic traditions that persisted under the surface of imposed religion. Recognizing this history matters for understanding why reclaiming indigenous magical traditions carries deep political significance today.", zh: "在欧洲以外，土著魔法实践与殖民主义之间存在着复杂的关系。在美洲、非洲和亚洲，殖民当局和传教士经常将当地的治愈传统、占卜体系和灵媒活动定为犯罪——以「巫术」之名来否定整个世界观的合法性。海地的伏都教、巴西的坎多姆布雷和古巴的桑特里亚，都通过将非洲精神实践与天主教图像创造性地融合而得以存续，在强加的宗教表面之下形成了混合传统。认识这段历史，对于理解今天重新认领土著魔法传统何以具有深刻政治意义至关重要。" },
    { en: "In the twentieth century, Wicca emerged as the most influential form of modern Western paganism. Founded largely through the writings of Gerald Gardner in 1950s England and later shaped by Doreen Valiente and others, Wicca synthesizes ceremonial magic, folk witchcraft, and nature-reverence into a structured initiatory religion centered on a Goddess and a Horned God. The Wheel of the Year — eight seasonal sabbats — structures Wiccan ritual practice. From the 1970s onward, feminist and eclectic witchcraft movements expanded far beyond Gardner's original coven system, and today \"witch\" is widely self-claimed as an identity by practitioners ranging from strict traditionalists to solitary eclectics blending astrology, tarot, herbal magic, and social-justice spirituality.", zh: "二十世纪，威卡教作为现代西方异教中最具影响力的形式而兴起。它主要通过杰拉尔德·加德纳在1950年代英格兰的著作奠定基础，后经多琳·瓦利安特等人进一步塑造，将仪式魔法、民间巫术与自然崇敬综合为一种以女神和有角之神为核心的结构化传承宗教。「年轮」——八个季节性安息日——构成了威卡仪式实践的框架。从1970年代起，女性主义和折衷巫术运动大幅超越加德纳最初的女巫集会体系，如今「女巫」一词被从严格的传统主义者到融合占星、塔罗、草药魔法与社会正义灵性的孤独折衷修行者，广泛地用作自我认同标签。" },
    { en: "Anthropologists and scholars of religion approach magic not as supernatural reality or absurd superstition but as a meaningful symbolic system. Ritual action — lighting a candle, reciting a formula, creating a protective amulet — can produce genuine psychological effects: reinforcing intention, reducing anxiety, marking thresholds, and building community solidarity. The study of magic invites reflection on the boundaries between prayer, ritual, placebo, and art, and on why human minds so persistently seek to act upon the world through symbolic means.", zh: "人类学家和宗教学者对待魔法，既不将其视为超自然现实，也不将其斥为荒诞迷信，而是将其视为一套有意义的象征符号体系。仪式行为——点燃蜡烛、诵念咒语、制作护身符——能够产生真实的心理效果：强化意图、减轻焦虑、标记人生阈限，以及凝聚社区认同。对魔法的研究促使我们反思祈祷、仪式、安慰剂与艺术之间的边界，以及人类心灵为何如此执着地寻求通过象征性手段作用于世界。" },
  ],
  cards: [
    { icon: "🌿", title: { en: "Folk Magic & Cunning Craft", zh: "民间魔法与智慧术" }, body: { en: "Across pre-industrial Europe, 'cunning folk' offered healing, divination, and counter-charms. Their craft drew on herbalism, astrology, and local spirit lore — distinct from high ceremonial magic and largely tolerated by communities despite Church suspicion.", zh: "在前工业化的欧洲，「聪明人」提供治愈、占卜和解咒服务。他们的技艺融合了草药学、占星术和当地灵体传说——有别于高级仪式魔法，尽管受到教会的疑忌，在社区中大体上受到容忍。" } },
    { icon: "🔥", title: { en: "The Witch-Hunts", zh: "猎巫运动" }, body: { en: "Between 1450 and 1750, European courts executed 40,000–60,000 people for alleged witchcraft. The Malleus Maleficarum (1487) codified the theology of diabolism. Most victims were women; trials relied on torture. Historians view the hunts as driven by social crisis, misogyny, and inquisitorial procedure.", zh: "1450至1750年间，欧洲法庭以巫术罪名处决了四至六万人。《女巫之锤》（1487年）将魔鬼崇拜的神学体系化。受害者大多为女性；审判依赖酷刑。历史学家认为猎巫运动的根源在于社会危机、厌女情结和宗教裁判所的程序。" } },
    { icon: "🌍", title: { en: "African & Diaspora Traditions", zh: "非洲及离散社区传统" }, body: { en: "Vodou, Candomblé, and Santería are syncretic traditions forged when enslaved Africans preserved Yoruba, Fon, and Kongo spiritual practices under Catholic disguise. They feature spirit possession, ritual healing, divination systems (like Ifá), and rich ceremonial music and dance.", zh: "伏都教、坎多姆布雷和桑特里亚是混合传统，由被奴役的非洲人在天主教外衣下保存约鲁巴、丰族和刚果的精神实践而形成。它们的特征是灵魂附体、仪式治愈、占卜体系（如伊法），以及丰富的仪式音乐与舞蹈。" } },
    { icon: "🌙", title: { en: "Wicca & Modern Witchcraft", zh: "威卡教与现代巫术" }, body: { en: "Wicca, shaped by Gerald Gardner and Doreen Valiente in 1950s Britain, venerates a dual deity (Goddess and Horned God) and observes eight seasonal sabbats. Since the 1970s, feminist witchcraft movements have democratized practice far beyond initiatory covens, making 'witch' a widely embraced identity worldwide.", zh: "威卡教由杰拉尔德·加德纳和多琳·瓦利安特在1950年代的英国塑造，崇拜二元神灵（女神与有角之神），庆祝八个季节性安息日。自1970年代以来，女性主义巫术运动将实践大幅民主化，远超传承女巫集会的范畴，使「女巫」成为全球广泛接受的身份认同。" } },
    { icon: "🪄", title: { en: "Ceremonial Magic", zh: "仪式魔法" }, body: { en: "Ceremonial or high magic traces to Renaissance Hermeticism, the Kabbalah, and grimoire traditions. The Hermetic Order of the Golden Dawn (1880s) and Aleister Crowley's Thelema systematized angel-conjuration, elemental workings, and initiatory grades. Their influence flows into Wicca, chaos magic, and contemporary occultism.", zh: "仪式魔法或高级魔法的源头可追溯至文艺复兴时期的赫耳墨斯主义、卡巴拉和魔典传统。黄金黎明赫耳墨斯团（1880年代）和阿莱斯特·克劳利的泰勒玛将天使召唤、元素操作与传承等级系统化。其影响渗透到威卡教、混沌魔法和当代神秘主义中。" } },
    { icon: "🌱", title: { en: "Shamanic & Indigenous Magic", zh: "萨满与土著魔法" }, body: { en: "Indigenous healers — curanderas, sangomas, jom — combine plant medicine, spirit communication, and ritual to address illness, conflict, and community imbalance. Colonialism criminalized many such practices; today, indigenous communities assert the right to revitalize them on their own terms.", zh: "土著治愈者——萨满医者、桑古玛、约姆——将植物医学、灵体沟通和仪式结合起来，以解决疾病、冲突和社区失衡问题。殖民主义将许多此类实践定为犯罪；如今，土著社区正在主张以自己的方式振兴这些传统。" } },
    { icon: "⚗️", title: { en: "Magic as Symbolic Technology", zh: "作为象征技术的魔法" }, body: { en: "Anthropologist Bronisław Malinowski observed that Trobriand Islanders used garden magic for predictable cultivation but turned to canoe magic for dangerous open-sea voyaging — magic addresses the gap between skill and uncertainty. Scholars view ritual magic as a symbolic technology that shapes intention, manages anxiety, and creates social solidarity.", zh: "人类学家布罗尼斯拉夫·马林诺夫斯基观察到，特罗布里恩德岛民在可预期的耕作中使用花园魔法，而在危险的远海航行中则求助于独木舟魔法——魔法填补了技能与不确定性之间的空白。学者将仪式魔法视为一种象征技术，它塑造意图、管理焦虑并创造社会凝聚力。" } },
    { icon: "🔮", title: { en: "Divination Across Cultures", zh: "跨文化占卜" }, body: { en: "From Chinese I Ching and Yoruba Ifá to tarot cards and Greek oracles, divination systems share a common logic: externalizing decision-making through a structured randomizing process that invites reflection. Psychologically, the process can clarify unconscious priorities rather than reveal objective futures.", zh: "从中国的《易经》、约鲁巴的伊法，到塔罗牌和希腊神谕，占卜体系共享一种共同逻辑：通过结构化的随机过程将决策外部化，从而引发反思。从心理学角度来看，这一过程能够澄清潜意识的优先考量，而非揭示客观的未来。" } },
  ],
  questions: [
    { q: { en: "Why were women disproportionately targeted in the witch-hunts?", zh: "为何女性在猎巫运动中受到了不成比例的迫害？" }, a: { en: "Theological suspicion of female sexuality, the social marginality of widows and healers, and legal structures that made women easier targets all combined. Gender anxiety and property disputes were often the underlying triggers for specific accusations.", zh: "神学上对女性性欲的怀疑、寡妇和治愈者的社会边缘地位，以及使女性更易成为目标的法律结构，共同造成了这一局面。性别焦虑和财产纠纷往往是具体指控背后的潜在诱因。" } },
    { q: { en: "Is modern Wicca connected to ancient pre-Christian religion?", zh: "现代威卡教与古代前基督教宗教有关联吗？" }, a: { en: "Wicca claims symbolic continuity with pre-Christian nature religion but is largely a 20th-century creation. Gardner drew on ceremonial magic, Freemasonry, and 19th-century Romanticism rather than documented ancient practice. This does not diminish its spiritual significance to practitioners.", zh: "威卡教声称与前基督教的自然宗教在象征层面上具有连续性，但它在很大程度上是一种二十世纪的创造。加德纳借鉴的是仪式魔法、共济会和19世纪浪漫主义，而非有据可查的古代实践。这并不削弱其对实践者的精神意义。" } },
  ],
  viz: "cards",
};
export default sec;
