import type { Section } from "@/lib/types";
const sec: Section = {
  id: "alchemy",
  num: 15,
  kicker: { en: "Section 15 · The Art of Transformation", zh: "第十五章 · 转化之术" },
  title: { en: "Alchemy", zh: "炼金术" },
  lead: { en: "Alchemy was never merely the attempt to make gold — it was a total philosophy of transformation: the conviction that matter, soul, and cosmos are governed by the same hidden principles, and that the patient, disciplined practitioner could participate in creation's ongoing self-perfection.", zh: "炼金术从来不仅仅是制造黄金的尝试——它是一套完整的转化哲学：相信物质、灵魂与宇宙受同一隐秘原则支配，相信耐心、自律的修炼者能够参与宇宙自我完善的持续进程。" },
  body: [
    { en: "Alchemy emerged in antiquity as a craft tradition concerned with dyeing, metalwork, glass-making, and the apparent transmutation of base metals. But it rapidly acquired a cosmological and spiritual dimension. The alchemist's laboratory was simultaneously a philosophical theater: the operations performed on matter — dissolution, putrefaction, calcination, distillation, coagulation — were understood to mirror processes occurring in nature, in the cosmos, and in the practitioner's own soul. The famous motto solve et coagula ('dissolve and coagulate') captured the double movement: breaking structures apart to reveal their hidden essence, then reconstructing them in a higher form.", zh: "炼金术在古代作为一种与染料、金属加工、玻璃制造以及贱金属表面嬗变相关的工艺传统而兴起。但它很快获得了宇宙论与精神层面的维度。炼金士的实验室同时也是一座哲学剧场：对物质施行的操作——溶解、腐败、煅烧、蒸馏、凝固——被理解为映射着自然、宇宙以及修炼者自身灵魂中发生的过程。著名格言\"溶解与凝固\"（solve et coagula）捕捉了这一双重运动：分解结构以揭示其隐藏本质，然后以更高形式重新构建。" },
    { en: "Western alchemy crystallized in Hellenistic Egypt — particularly in Alexandria — where Greek philosophical ideas (Aristotelian four elements, Platonic archetypes), Egyptian craft traditions, and Jewish and Gnostic mysticism merged. The legendary figure of Hermes Trismegistus ('Thrice-Great Hermes') was credited as the founding father, and the Emerald Tablet attributed to him encapsulated the alchemical worldview in a few enigmatic lines: 'As above, so below' — the macrocosm and microcosm reflect each other. Arabic scholars preserved and extended this tradition through the medieval period; Jabir ibn Hayyan (Geber) systematized alchemical theory and practice in the 8th century, and his works passed into Latin Europe, fueling centuries of research.", zh: "西方炼金术在希腊化时代的埃及——尤其是亚历山大里亚——结晶成形，在那里，希腊哲学思想（亚里士多德的四元素、柏拉图的理型）、埃及工艺传统、犹太与诺斯底神秘主义融合在一起。传奇人物赫尔墨斯·特里斯墨吉斯托斯（\"三倍伟大的赫尔墨斯\"）被奉为奠基之父，归于其名下的《翠玉录》用寥寥数行神秘文字概括了炼金术的世界观：\"上如其下，下如其上\"——宏观宇宙与微观宇宙相互映照。阿拉伯学者在中世纪保存并发展了这一传统；8世纪的贾比尔·伊本·哈扬（格伯）系统化了炼金理论与实践，其著作传入拉丁欧洲，催生了数百年的研究。" },
    { en: "The central quest of Western alchemy was the Philosopher's Stone — a legendary substance that could transmute base metals into gold and serve as the elixir of eternal life. These goals should be read on multiple levels. Materially, they drove genuine proto-chemical research: alchemists discovered phosphorus, developed distillation apparatus, and anticipated many chemical reactions. Spiritually, the Stone represented the perfected self — the purified soul that had undergone the same death-and-resurrection cycle as matter in the alembic. The nigredo (blackening, death), albedo (whitening, purification), citrinitas (yellowing), and rubedo (reddening, completion) were both laboratory stages and spiritual passages.", zh: "西方炼金术的核心追求是\"哲人石\"——一种传说中的物质，能将贱金属嬗变为黄金，并充当永生的灵丹妙药。这些目标应在多个层面上解读。在物质层面，它们推动了真正的原始化学研究：炼金士发现了磷，发展了蒸馏装置，并预示了许多化学反应。在精神层面，哲人石代表着完善的自我——经历了与蒸馏器中物质相同的死亡与复活循环的纯化灵魂。黑化（nigredo，变黑、死亡）、白化（albedo，变白、净化）、黄化（citrinitas）以及红化（rubedo，变红、完成）既是实验室的操作阶段，也是精神历程的阶段。" },
    { en: "Chinese alchemy developed along parallel but distinct lines. Waidan ('outer alchemy') sought physical immortality through the ingestion of refined elixirs — often perilously toxic concoctions of mercury, lead, and sulfur. Chinese emperors who sought the elixir of life were sometimes poisoned by it. Neidan ('inner alchemy') — which emerged as a response to waidan's dangers and limitations — relocated the entire process inside the body. The practitioner's body became the furnace; breath, essence (jing), vitality (qi), and spirit (shen) were the materials to be refined. Through meditative and breathing practices, these were circulated and transformed along inner pathways, ultimately to be returned to an original, undifferentiated state.", zh: "中国炼金术沿着平行但不同的路径发展。外丹追求通过服食精炼的丹药实现长生不老——这些配方通常含有危险的汞、铅与硫磺。一些寻求长生丹药的中国皇帝反被其毒害。内丹——作为对外丹危险性与局限性的回应而兴起——将整个炼化过程迁移至身体内部。修炼者的身体成为炉鼎；精、气、神是待精炼的材料。通过冥想与呼吸修炼，这些材料在内在脉络中循环流转，最终归还至一种原初的、未分化的状态。" },
    { en: "In the 20th century, Carl Jung proposed the most influential modern reading of Western alchemy. In works such as 'Psychology and Alchemy' (1944), Jung argued that the alchemists were engaged in a projection of unconscious psychological processes onto matter. The stages of the alchemical work — nigredo, albedo, rubedo — mapped onto the process of individuation: the psychological journey toward wholeness in which the shadow is confronted, the anima/animus integrated, and the Self realized. Jung did not dismiss alchemy as mere failed chemistry; he saw it as a genuine, if unconscious, exploration of the psyche's depths. This reading gave alchemy renewed intellectual respectability and connected it to the modern therapeutic tradition.", zh: "20世纪，卡尔·荣格提出了对西方炼金术最具影响力的现代解读。在《心理学与炼金术》（1944年）等著作中，荣格认为炼金士们是在将无意识的心理过程投射到物质之上。炼金工作的各个阶段——黑化、白化、红化——对应于个体化的过程：一段走向心理整全的旅程，在这一过程中，阴影被正视，阿尼玛/阿尼姆斯得到整合，自性（Self）得以实现。荣格并未将炼金术斥为失败的化学；他将其视为对心灵深处的真实探索，尽管是无意识的。这一解读赋予炼金术以新的学术价值，并将其与现代心理治疗传统相连接。" },
  ],
  cards: [
    { icon: "🔥", title: { en: "Transformation", zh: "转化" }, body: { en: "The master principle: nothing is fixed, everything can be refined to a higher state. Alchemy treated change not as decay but as purposeful process — the universe itself as an ongoing work of purification. This philosophical stance influenced early chemistry, medicine, and later depth psychology.", zh: "核心原则：没有什么是固定不变的，一切都可以被精炼为更高形态。炼金术将变化视为不是衰败而是有目的的过程——宇宙本身就是一项持续进行的净化工程。这一哲学立场影响了早期化学、医学以及后来的深度心理学。" } },
    { icon: "☿", title: { en: "Symbolism & the Emerald Tablet", zh: "象征与《翠玉录》" }, body: { en: "Alchemical texts are dense with symbols: the ouroboros (serpent eating its tail, endless cycle), the red king and white queen (sulfur and mercury, masculine and feminine principles), the hermaphrodite (unity of opposites). The Emerald Tablet's dictum 'as above, so below' declared the correspondence between cosmos and individual — the foundational axiom of the Hermetic tradition.", zh: "炼金术文本充满象征：衔尾蛇（吞食自身尾巴的蛇，无尽的循环）、红王与白后（硫磺与汞，男性与女性原则）、雌雄同体（对立面的统一）。《翠玉录》的格言\"上如其下\"宣告了宇宙与个体之间的对应关系——赫尔墨斯传统的基础公理。" } },
    { icon: "⚗️", title: { en: "Western Alchemy", zh: "西方炼金术" }, body: { en: "From Hellenistic Alexandria through Islamic Baghdad to medieval and Renaissance Europe, Western alchemy sought the Philosopher's Stone, universal solvent, and elixir of life. Its laboratories produced real chemical discoveries (phosphorus, mineral acids, distillation techniques) even as its cosmological framework remained pre-scientific. Figures: Jabir, Albertus Magnus, Paracelsus, Newton.", zh: "从希腊化时代的亚历山大里亚，经伊斯兰时代的巴格达，到中世纪与文艺复兴时期的欧洲，西方炼金术寻求哲人石、万能溶剂与生命灵药。其实验室在宇宙论框架仍属前科学的同时，产生了真实的化学发现（磷、矿物酸、蒸馏技术）。代表人物：贾比尔、大阿尔伯特、帕拉塞尔苏斯、牛顿。" } },
    { icon: "🧪", title: { en: "Chinese Waidan (外丹)", zh: "外丹" }, body: { en: "Outer alchemy: the laboratory refinement of minerals and herbs into elixirs for physical immortality. Associated with Daoist tradition, waidan reached its peak in the Tang Dynasty. Its hazardous materials — cinnabar, lead, mercury compounds — caused poisoning deaths, including several emperors. It eventually gave way to neidan as the dominant tradition.", zh: "外丹：在实验室中精炼矿物与草药以制成追求肉身长生的丹药。与道教传统相关，外丹在唐代达到鼎盛。其危险原料——朱砂、铅、汞化合物——造成中毒死亡，包括数位皇帝。它最终让位于内丹，成为历史。" } },
    { icon: "🧘", title: { en: "Chinese Neidan (内丹)", zh: "内丹" }, body: { en: "Inner alchemy: the body itself is the crucible, breath and consciousness the materials. Neidan practitioners cultivate jing (essence), qi (vitality), and shen (spirit) through meditative, breathing, and movement practices, circulating them along inner pathways to return to an original unity. This tradition profoundly shaped qigong, Taoist meditation, and Traditional Chinese Medicine.", zh: "内丹：身体本身是坩埚，气息与意识是材料。内丹修炼者通过冥想、呼吸与动功修炼精、气、神，使其沿内在脉络循环，以回归原初的统一。这一传统深刻影响了气功、道教冥想与中医传统。" } },
    { icon: "🧠", title: { en: "Jung's Reading", zh: "荣格的解读" }, body: { en: "Carl Jung argued that alchemy's symbolic opus was an unconscious map of psychological individuation. The alchemist projected inner psychological dynamics — shadow, anima, Self — onto chemical materials. The stages nigredo → albedo → rubedo correspond to confronting the shadow, integrating opposites, and realizing wholeness. Jung's reading salvaged alchemy as a serious object of psychological inquiry.", zh: "卡尔·荣格认为，炼金术的象征性工作是心理个体化过程的无意识地图。炼金士将内在心理动力——阴影、阿尼玛、自性——投射到化学材料上。黑化→白化→红化的阶段对应于正视阴影、整合对立面以及实现整全。荣格的解读使炼金术成为心理学探究的严肃对象。" } },
    { icon: "🌿", title: { en: "Paracelsus & the Medical Turn", zh: "帕拉塞尔苏斯与医学转向" }, body: { en: "The 16th-century Swiss physician-alchemist Paracelsus rejected Galenic medicine and argued that diseases had specific chemical causes and required chemical remedies. He introduced the use of minerals like mercury, arsenic, and sulfur in medicine — a radical turn that prefigured pharmaceutical chemistry. He also insisted the true goal of alchemy was healing the human body, not making gold.", zh: "16世纪瑞士医生兼炼金士帕拉塞尔苏斯拒绝盖伦医学，主张疾病有特定的化学原因，需要化学药物治疗。他将汞、砷、硫磺等矿物引入医学——这一激进转向预示了制药化学的兴起。他还坚持认为炼金术的真正目标是治愈人体，而非制造黄金。" } },
  ],
  questions: [
    { q: { en: "Was alchemy just failed chemistry?", zh: "炼金术只是失败的化学吗？" }, a: { en: "Partly, but reductively so. Alchemists made genuine chemical discoveries and laid groundwork for modern chemistry. But they operated within a different epistemic framework — one in which matter was alive, purposive, and resonant with meaning. Understood on its own terms, alchemy was a coherent practice combining natural philosophy, craft, and spiritual discipline. Dismissing it entirely misses what drove centuries of rigorous inquiry.", zh: "部分正确，但这一说法过于简化。炼金士们做出了真实的化学发现，为现代化学奠定了基础。但他们在不同的认识论框架内运作——在那个框架中，物质是有生命的、有目的的、充满意义共鸣的。在自身语境中理解，炼金术是将自然哲学、工艺与精神修炼结合的一套连贯实践。将其全盘否定，就错失了驱动数百年严格探究的动力所在。" } },
  ],
  viz: "cards",
  vizTitle: { en: "The Alchemical Tradition", zh: "炼金术传统" },
  accent: "#e8c074",
};
export default sec;
