import type { Section } from "@/lib/types";
const sec: Section = {
  id: "shamanism",
  num: 10,
  kicker: { en: "Section 10 · Between Worlds", zh: "第十章 · 诸界之间" },
  title: { en: "Shamanism", zh: "萨满宇宙" },
  lead: { en: "Shamanism is perhaps humanity's oldest living religious complex: a constellation of practices found on every inhabited continent, in which specially gifted individuals enter altered states to journey between cosmic realms, heal, divine, and negotiate with spirits on behalf of their communities.", zh: "萨满教也许是人类最古老的、至今仍在活态传承的宗教综合体：一套遍布各大洲的实践体系，其中具有特殊禀赋的个体通过进入变异意识状态，在不同宇宙层次间穿行，代表社群治愈病患、占卜未来、与灵界交涉。" },
  body: [
    { en: "The word 'shaman' comes from the Evenki language of Siberia — saman, meaning 'one who knows' — but the phenomenon it describes appears across Arctic, Siberian, Central Asian, Indigenous American, Amazonian, African, and South and Southeast Asian cultures. While each tradition is unique, anthropologists identify recurring structural features: a three-tiered cosmos (upper, middle, and lower worlds), the shaman as ritual specialist, spirit helpers or allies, and the use of altered states — induced by drumming, fasting, plant medicines, or sustained isolation — to access non-ordinary realms.", zh: "「萨满」一词来自西伯利亚鄂温克语——saman，意为“知晓者”——但它所描述的现象广泛出现于北极、西伯利亚、中亚、美洲原住民、亚马逊、非洲以及南亚、东南亚各文化之中。尽管每个传统各具特色，人类学家仍识别出若干反复出现的结构性特征：三层宇宙（上界、中界与下界）、作为仪式专家的萨满、精灵助手或盟友，以及借助鼓击、禁食、植物药物或长期隔离所引发的变异意识状态来进入非常规领域的实践。" },
    { en: "Central to shamanic cosmology is the notion that illness, misfortune, and social disruption often have a spiritual cause — a lost or stolen soul, an offended ancestor, an unbalanced relationship with the natural world. The shaman's primary vocation is diagnostic and therapeutic: to perceive the invisible causes of visible suffering and restore harmony through ritual action. This makes shamanism, in many respects, both a medical and a judicial system, as well as a religious one.", zh: "萨满宇宙观的核心是这样一种理念：疾病、厄运与社会混乱往往具有灵性根源——失落或被盗的灵魂、受到冒犯的祖先、与自然世界失衡的关系。萨满的主要使命在于诊断与治疗：感知可见苦难背后的不可见原因，并通过仪式行动恢复和谐。在许多方面，这使萨满教同时成为一套医疗体系、一套司法体系与一套宗教体系。" },
    { en: "Drum and rhythm are near-universal shamanistic tools. Ethnomusicologists have documented that sustained rhythmic drumming at certain frequencies (typically 4–7 Hz) can shift brainwave states, facilitating the trance-like focus associated with shamanic journeying. The drum is often described as the shaman's 'spirit horse' or 'canoe' — the vehicle of travel between worlds. Song, chant, and specific sacred languages also play central roles in calling spirits and maintaining ceremonial order.", zh: "鼓与节奏是几乎放之四海而皆准的萨满工具。民族音乐学家已证明，在特定频率（通常为4至7赫兹）下持续的节奏性击鼓能够改变脑波状态，有助于进入与萨满旅程相关的出神专注状态。鼓常被描述为萨满的「灵马」或「独木舟」——在诸界之间穿行的交通工具。歌唱、吟咏与特定神圣语言在召唤灵体、维持仪式秩序方面同样扮演着核心角色。" },
    { en: "Contemporary shamanism raises important questions about cultural appropriation, commodification, and authenticity. In the late 20th century, 'neo-shamanism' or 'core shamanism' — popularised by figures like Michael Harner — extracted techniques from Indigenous contexts and repackaged them for Western spiritual seekers. Indigenous scholars and community leaders have frequently criticized this, pointing to the loss of cultural context, the commercialisation of sacred practices, and the ongoing legacy of colonialism that stripped many communities of their traditional practitioners in the first place.", zh: "当代萨满教引发了关于文化挪用、商品化与真实性的重要争论。20世纪晚期，「新萨满教」或「核心萨满教」——由迈克尔·哈纳等人推广——将技术从原住民语境中剥离出来，重新包装以迎合西方灵性追求者。原住民学者和社区领袖对此提出频繁批评，指出神圣实践丧失了文化语境、遭到商业化，以及殖民主义的历史遗产本身早已剥夺了许多社群的传统实践者。" },
    { en: "Despite pressures from missionary Christianity, Islam, and Soviet-era suppression in Siberia and Central Asia, shamanic traditions have proven extraordinarily resilient. In Mongolia, Buryatia, and among many Indigenous peoples of the Americas and Amazonia, there are active revivals. Researchers across medical anthropology, cognitive science, and psychology are increasingly interested in what shamanic practices reveal about the nature of healing, consciousness, and the brain's capacity to reframe reality through ritual.", zh: "尽管面临基督教传教、伊斯兰教以及苏联时期对西伯利亚和中亚的压制，萨满传统展现出非凡的韧性。在蒙古、布里亚特，以及美洲和亚马逊的许多原住民群体中，都出现了积极的复兴运动。医学人类学、认知科学与心理学领域的研究者对萨满实践越来越感兴趣，希望从中了解治愈的本质、意识的性质，以及大脑通过仪式重构现实的能力。" },
  ],
  cards: [
    { icon: "🌌", title: { en: "The Spirit Journey", zh: "灵魂之旅" }, body: { en: "The defining shamanic act: the practitioner enters a trance state and travels — often as an animal or spirit-self — through the layered cosmos to retrieve souls, consult spirits, or bring back healing knowledge. The journey is experienced as vivid and real.", zh: "萨满实践的核心行为：实践者进入出神状态，通常化身为动物或灵体，穿越多层宇宙，以取回灵魂、咨询灵体或带回疗愈知识。这段旅程被体验为生动而真实的经历。" } },
    { icon: "👴", title: { en: "Ancestors", zh: "祖先灵" }, body: { en: "The spirits of the dead — especially lineage ancestors — are active participants in shamanic cosmology. They can protect, guide, punish, or cause illness. Maintaining right relationship with ancestors through offerings and ceremony is a central social obligation in many shamanic cultures.", zh: "逝者之灵——尤其是血脉祖先——在萨满宇宙观中是活跃的参与者。他们能够庇护、引导、惩罚，也能带来疾病。在许多萨满文化中，通过供奉与仪式维持与祖先的正确关系，是重要的社会义务。" } },
    { icon: "🐺", title: { en: "Totems & Spirit Helpers", zh: "图腾与灵体助手" }, body: { en: "Shamans cultivate relationships with specific animal spirits — power animals or totems — that serve as allies, guides, and sources of spiritual power. Different animals carry different qualities: bear for healing strength, eagle for vision, serpent for transformation.", zh: "萨满与特定动物灵体——力量动物或图腾——建立关系，这些灵体充当盟友、向导与灵性力量的来源。不同动物携带不同特质：熊代表疗愈之力，鹰象征洞察之眼，蛇寓意转化与蜕变。" } },
    { icon: "🥁", title: { en: "Ritual & Drumming", zh: "仪式与击鼓" }, body: { en: "Ceremony creates a structured container for spiritual encounter. Shamanic rituals may involve drumming, rattling, chanting, dancing, the use of sacred objects, and carefully prescribed sequences of action that open communication with the spirit world and protect participants from harm.", zh: "仪式为灵性接触创造了有序的容器。萨满仪式可能涵盖击鼓、摇响器、吟唱、舞蹈、使用神圣器物，以及精心规定的行动序列，以开启与灵界的沟通并保护参与者免受伤害。" } },
    { icon: "💫", title: { en: "Trance & Dream States", zh: "出神与梦境" }, body: { en: "Altered states — whether induced by rhythm, breath, fasting, sacred plants, or sleep — are the primary mode of access to shamanic knowledge. Dreams are often regarded as communications from spirits or ancestors, requiring interpretation by the shaman. Lucid dreaming and vision quests are formalized practices in many traditions.", zh: "变异意识状态——无论由节奏、呼吸、禁食、神圣植物还是睡眠所引发——是获取萨满知识的主要途径。梦境常被视为灵体或祖先的传递，需要萨满加以诠释。清醒梦与异象追寻在许多传统中是正式的修炼方式。" } },
    { icon: "🌿", title: { en: "Plant Medicines", zh: "植物药物" }, body: { en: "Many shamanic traditions use psychoactive plants — ayahuasca in Amazonia, peyote among Native American peoples, psilocybin mushrooms in Mesoamerica, fly agaric in Siberia — as sacramental technologies for accessing visionary states. These are embedded in elaborate ceremonial contexts, not used recreationally.", zh: "许多萨满传统使用致幻植物——亚马逊的死藤水、北美原住民的仙人掌碱、中美洲的裸盖菇素蘑菇、西伯利亚的毒蝇伞——作为进入异象状态的圣礼技术。这些植物嵌入于精心设计的仪式语境中使用，而非用于娱乐目的。" } },
    { icon: "🗺", title: { en: "Cosmic Geography", zh: "宇宙地理" }, body: { en: "Most shamanic cosmologies map existence as three or more stacked worlds — an upper realm of sky spirits and celestial beings, a middle realm of human life, and a lower realm of earth spirits and ancestors — connected by a central axis mundi: world tree, mountain, or pillar.", zh: "大多数萨满宇宙观将存在描绘为三层或多层叠加的世界——天空灵体与天界存在所居的上界、人类生活所处的中界、地之灵与祖先所在的下界——由一根中心世界轴相连：世界树、神山或宇宙柱。" } },
  ],
  questions: [
    { q: { en: "Is shamanism a religion, a medical system, or something else entirely?", zh: "萨满教是宗教、医疗体系，还是完全不同的东西？" }, a: { en: "It resists easy categorisation. Shamanism is not a creed or a church — it has no fixed theology, no canonical texts, and no centralised authority. It is better understood as a set of technologies for navigating the relationship between visible and invisible realities, one that integrates healing, cosmology, social regulation, and meaning-making into a single practice tradition. Many scholars prefer the term 'shamanic complex' to avoid the reifying implications of '-ism'.", zh: "它难以归入固定类别。萨满教并非信条或教会——它没有固定神学、没有权威典籍、没有中央权威机构。更好的理解方式是将其视为一套应对可见与不可见现实之间关系的技术体系，将治疗、宇宙观、社会规范与意义建构整合于单一的实践传统之中。许多学者更倾向于使用「萨满综合体」一词，以避免「主义」所隐含的本质化含义。" } },
    { q: { en: "What can modern science learn from shamanic traditions?", zh: "现代科学能从萨满传统中学到什么？" }, a: { en: "Researchers in psychiatry and neuroscience are studying ritualised altered states — including ayahuasca ceremonies — for their potential therapeutic applications in treating depression, PTSD, and addiction. Medical anthropologists note that shamanic healing often works through the 'meaning response': the mobilisation of the body's own healing resources through culturally powerful ritual. Cognitive scientists study how the shamanic world-model represents an early solution to the same problems of agency, causality, and social prediction that the human mind evolved to solve.", zh: "精神病学与神经科学领域的研究者正在研究仪式化变异意识状态——包括死藤水仪式——在治疗抑郁症、创伤后应激障碍和成瘾方面的潜在疗愈应用。医学人类学家注意到，萨满疗愈往往通过「意义反应」发挥作用：借助文化上具有强大力量的仪式，调动身体自身的疗愈资源。认知科学家则研究萨满世界模型如何呈现出针对同一批问题——能动性、因果关系与社会预测——的早期解决方案，而这些问题正是人类心智进化所要应对的核心挑战。" } },
  ],
  viz: "cards",
  accent: "#ff8fb0",
};
export default sec;
