import type { Section } from "@/lib/types";
const sec: Section = {
  id: "mysticism",
  num: 14,
  kicker: { en: "Section 14 · The Inner Flame", zh: "第十四章 · 内在之火" },
  title: { en: "Mysticism", zh: "神秘主义" },
  lead: { en: "Across every major tradition, a current of seekers has pursued direct, immediate experience of ultimate reality — not belief about the divine, but union with it — producing a surprisingly convergent literature of inner transformation and ineffable encounter.", zh: "在每一个主要传统之中，都有一股寻道者的潜流，追求对终极实在的直接、即刻体验——不是关于神圣的信念，而是与之合一——由此产生了一部令人惊异地高度趋同的内在转化与不可言说相遇的文献。" },
  body: [
    { en: "Mysticism names the pursuit of direct experiential union with ultimate reality — whether understood as God, the Absolute, the Tao, Brahman, or Buddha-nature. Where orthodox religion often operates through doctrine, scripture, and communal ritual, the mystic insists that these are at best vehicles pointing toward an experience that must finally be lived from the inside. Mystics appear as a minority strand within every major tradition, frequently in tension with religious establishments that find their claims of direct divine access unsettling or presumptuous.", zh: "神秘主义指对与终极实在——无论理解为神、绝对者、道、梵还是佛性——直接体验性合一的追求。正统宗教往往通过教义、经典与共同体仪式运作，而神秘主义者则坚持认为，这些充其量只是指向一种体验的载体，而这种体验最终必须从内部去活出。神秘主义者作为少数脉络出现在每一个主要传统中，常与宗教权威机构处于张力之中，后者认为他们声称直接获得神圣接触的说法令人不安或傲慢。" },
    { en: "Despite arising in profoundly different cultural and theological contexts, mystics across traditions share a cluster of recurring themes: an intense longing for union with the divine source; practices of purification, silence, and contemplation; the paradoxical use of language — metaphor, poetry, apophatic negation — to gesture at what cannot be said; an experience often described as light, love, or boundless consciousness; and a subsequent transformation of character toward compassion and detachment from ego. The philosopher William James identified mystical experience as noetic (conveying genuine knowledge), transient, passive (felt as given, not achieved), and ineffable.", zh: "尽管产生于截然不同的文化与神学背景，各传统的神秘主义者却共享着一系列反复出现的主题：对与神圣源泉合一的强烈渴望；净化、静默与沉思的修炼；悖论性地使用语言——隐喻、诗歌、否定神学——指向那不可言说之物；一种常被描述为光、爱或无边意识的体验；以及随后人格向慈悲与离执的转化。哲学家威廉·詹姆斯将神秘体验定性为：认知性的（传递真实知识）、短暂的、被动的（感觉是被给予而非主动获得）以及不可言说的。" },
    { en: "Christian mysticism has a rich history running from the Desert Fathers and Pseudo-Dionysius (who developed the apophatic tradition: God is best approached by saying what God is not) through medieval masters like Meister Eckhart, Hildegard of Bingen, Julian of Norwich, and John of the Cross. Eckhart's teaching that there is a 'spark of the soul' identical with God's own being brought him to the edge of heresy trial. John of the Cross charted the 'dark night of the soul' — a harrowing spiritual desolation that precedes deeper union — a map of transformation that resonates across traditions.", zh: "基督教神秘主义有着丰富的历史：从沙漠教父与伪狄奥尼修斯（后者发展了否定神学传统：通过说神不是什么来最好地接近神），经过中世纪大师爱克哈特大师、宾根的希尔德嘉德、诺里奇的朱利安和十字约翰。爱克哈特关于灵魂中存在一个与神自身本体相同的\"火花\"的教导，使他险些面临异端审判。十字约翰绘制了\"灵魂的黑夜\"——一种先于更深合一的灵性荒凉——这一转化地图在各传统中引发共鸣。" },
    { en: "Sufism is Islamic mysticism — an interior path that seeks the immediate experience of divine love and the annihilation of the ego in God (fana). The 13th-century poet Rumi, the philosopher Ibn Arabi, and al-Hallaj (who was executed for declaring 'I am the Truth') are its luminaries. Sufi orders (tariqas) transmit techniques of dhikr (rhythmic repetition of divine names), sama (devotional music and whirling), and breath work under the guidance of a master (shaykh). Kabbalah, the Jewish mystical tradition, maps divine reality through the ten Sefirot — emanations of Ein Sof ('the Infinite') — and reads scripture as a layered cipher encoding hidden divine architecture.", zh: "苏菲主义是伊斯兰神秘主义——一条寻求神圣之爱的直接体验以及自我在神中消融（芬纳）的内在道路。13世纪诗人鲁米、哲学家伊本·阿拉比以及哈拉智（因宣称\"我即真理\"而被处决）是其代表人物。苏菲道团（tariqa）在导师（谢赫）指引下传授迪克尔（神名的节律性重复）、萨玛（虔信音乐与旋转舞蹈）以及呼吸修炼等技法。卡巴拉是犹太神秘主义传统，通过十个圆质（Sefirot）——无限（Ein Sof）的流溢——来绘制神圣实在的地图，并将经典解读为编码隐藏神圣结构的多层密文。" },
    { en: "Eastern mystical traditions — particularly Advaita Vedanta and Zen Buddhism — share the goal of dissolving the illusion of a separate self. Advaita's jnana path uses radical self-inquiry (Who am I?) to expose the ego as a superimposition on pure awareness. Zen cuts through conceptual thought with paradoxical koans and intensive sitting (zazen), aiming at kensho or satori: sudden, direct insight into one's Buddha-nature. These traditions tend toward immanence — the divine is not elsewhere but identical with present awareness — while Western mystical traditions often retain a distinction between creature and creator even at the summit of union. The cross-cultural study of mysticism raises deep questions: are all mystics touching the same reality, or are the experiences profoundly shaped by the conceptual frameworks in which seekers are trained?", zh: "东方神秘主义传统——尤其是不二吠檀多与禅宗——共同以消解分离自我的幻觉为目标。不二吠檀多的智慧之道（jnana）运用彻底的自我探询（\"我是谁？\"）来揭示自我不过是叠加在纯粹觉知之上的假象。禅宗以悖论性的公案与密集的坐禅斩断概念思维，指向见性或悟道：对自身佛性的突然直接洞见。这些传统倾向于内在超越——神圣并非在别处，而是与当下觉知同一——而西方神秘主义传统即便在合一的顶点，往往仍保留着造物主与受造物之间的区别。神秘主义的跨文化研究提出了深刻的问题：所有神秘主义者是否都在触及同一实在，抑或这些体验被修行者所受训练的概念框架深刻塑造？" },
  ],
  cards: [
    { icon: "✝️", title: { en: "Christian Mysticism", zh: "基督教神秘主义" }, body: { en: "From the Desert Fathers' contemplative silence to Eckhart's Godhead beyond God, and John of the Cross's dark night of the soul — Christian mysticism charts union with a personal yet ineffable God through purgation, illumination, and union.", zh: "从沙漠教父的沉思静默，到爱克哈特超越神的神性，再到十字约翰的灵魂黑夜——基督教神秘主义通过净化、启蒙与合一三个阶段，绘制与人格性却不可言说之神合一的道路。" } },
    { icon: "☪️", title: { en: "Sufism (Islamic Mysticism)", zh: "苏菲主义（伊斯兰神秘主义）" }, body: { en: "The path of divine love in Islam. Sufi masters like Rumi and Ibn Arabi taught annihilation of the ego (fana) in God. Practices of dhikr, sama, and breathwork under a master's guidance carry the seeker toward the experience of divine unity (tawhid) lived from within.", zh: "伊斯兰中的神圣之爱道路。鲁米、伊本·阿拉比等苏菲大师教导自我在神中的消融（芬纳）。在导师指引下修习迪克尔、萨玛与呼吸法，引领求道者走向从内部活出的神圣合一（认主独一）体验。" } },
    { icon: "✡️", title: { en: "Kabbalah (Jewish Mysticism)", zh: "卡巴拉（犹太神秘主义）" }, body: { en: "A mystical map of divine emanation. The ten Sefirot describe how the Infinite (Ein Sof) flows into creation through successive attributes — Crown, Wisdom, Understanding down to Kingdom. Study, meditation, and ethical refinement allow the mystic to ascend these rungs toward union with the divine light.", zh: "神圣流溢的神秘地图。十个圆质（Sefirot）描述无限（Ein Sof）如何通过依次的属性——王冠、智慧、理解，直至王国——流入创造之中。通过研究、冥想与道德精炼，神秘主义者得以攀登这些阶梯，走向与神圣之光的合一。" } },
    { icon: "🕉", title: { en: "Advaita Vedanta", zh: "不二吠檀多" }, body: { en: "Hinduism's most radical non-dual philosophy. Adi Shankaracharya taught that Atman is Brahman — individual consciousness is identical with universal consciousness. The path of jnana (knowledge) uses direct self-inquiry to see through the illusion of the separate self and recognize ever-present, boundless awareness.", zh: "印度教最为彻底的不二哲学。阿迪·商羯罗教导：自我即是梵——个体意识与宇宙意识同一。智慧（jnana）之道运用直接的自我探询，看穿分离自我的幻觉，认识到永远当下的无边觉知。" } },
    { icon: "☸️", title: { en: "Zen Buddhism", zh: "禅宗" }, body: { en: "A tradition of direct transmission beyond words. Through koan practice and zazen, Zen aims at satori — sudden, direct insight into Buddha-nature that cannot be captured in doctrine. The Zen master uses unconventional means (shouts, blows, paradoxes) to break the student's reliance on conceptual thought.", zh: "一种超越文字的直接传授传统。通过公案修行与坐禅，禅宗指向悟道——对佛性的突然直接洞见，这一洞见无法被教义所捕捉。禅师运用非常规手段（喝叱、棒打、悖论）打破学人对概念思维的依赖。" } },
  ],
  questions: [
    { q: { en: "Is all mystical experience the same across traditions?", zh: "不同传统的神秘体验是同一的吗？" }, a: { en: "Perennialists like Aldous Huxley and Huston Smith argue yes: stripped of cultural clothing, mystics everywhere report the same unitive experience. Constructivists like Steven Katz counter that experience is never \"pure\" — it is always shaped by the concepts, practices, and expectations of the tradition in which one is trained. Both positions illuminate something real.", zh: "奥尔德斯·赫胥黎、休斯顿·史密斯等永恒哲学论者认为是的：剥去文化外衣，各地神秘主义者报告的都是同一种合一体验。史蒂文·卡茨等建构主义者则反驳：体验永远不是\"纯粹的\"——它始终被修行者所受训练的传统中的概念、实践与期望所塑造。两种立场都揭示了某种真实的东西。" } },
  ],
  viz: "comparison",
  vizTitle: { en: "Paths to Union", zh: "合一之道比较" },
  comparison: {
    aspect: { en: "The path to union with the divine", zh: "通向与神圣合一的道路" },
    dimensions: [
      { en: "Christian Mysticism", zh: "基督教神秘主义" },
      { en: "Sufism (Islamic)", zh: "苏菲主义（伊斯兰）" },
      { en: "Kabbalah (Jewish)", zh: "卡巴拉（犹太）" },
      { en: "Eastern (Advaita & Zen)", zh: "东方传统（不二吠檀多与禅）" },
    ],
    cells: [
      { en: "Via purgativa → illuminativa → unitiva. The soul is purified, illuminated by divine grace, and finally united with God while remaining a creature. Key figures: Meister Eckhart, John of the Cross, Julian of Norwich.", zh: "净化之路→启蒙之路→合一之路。灵魂得到净化，被神圣恩典启蒙，最终与神合一，同时仍保持受造物的身份。代表人物：爱克哈特大师、十字约翰、诺里奇的朱利安。" },
      { en: "Purification of the heart through love and remembrance (dhikr). The ego is annihilated (fana) in God, then the mystic subsists in God (baqa). The teacher-disciple bond is central. Rumi: \"Die before you die, and find there is no death.\"", zh: "通过爱与记忆（迪克尔）净化内心。自我在神中消融（芬纳），随后神秘主义者在神中持续存在（伴卡）。师徒关系是核心。鲁米：\"在死亡来临之前先死，你将发现并无死亡。\"" },
      { en: "Study of Torah as divine architecture; meditation on the Sefirot; ethical and spiritual refinement. The mystic seeks devekut — cleaving to God — and moves through the hidden meanings of scripture and divine names toward the Ein Sof.", zh: "将《托拉》研究为神圣结构；冥想十个圆质；道德与精神的精炼。神秘主义者寻求依附（Devekut）——依附于神——并通过经典与神圣名号的隐藏含义走向无限（Ein Sof）。" },
      { en: "Self-inquiry (Advaita: \"Who am I?\") or radical presence (Zen: zazen, koan). The separate self is seen through as illusion; what remains is pure, undivided awareness / Buddha-nature. No union with an external God — rather, recognition that the seeker was never separate.", zh: "自我探询（不二：\"我是谁？\"）或彻底的临在（禅：坐禅、公案）。分离的自我被看穿为幻觉；剩下的是纯粹、无分别的觉知/佛性。并非与外在神明的合一——而是认识到寻道者从未曾分离。" },
    ],
  },
  accent: "#a489ff",
};
export default sec;
