import type { Section } from "@/lib/types";
const sec: Section = {
  id: "hinduism",
  num: 13,
  kicker: { en: "Section 13 · The Eternal Dharma", zh: "第十三章 · 永恒之法" },
  title: { en: "Hinduism", zh: "印度教宇宙" },
  lead: { en: "The world's oldest living religion is not one doctrine but a vast, diverse conversation — spanning four millennia of philosophy, devotion, ritual, and cosmology — held together by shared concepts of Brahman, Dharma, and the soul's long journey toward liberation.", zh: "世界上最古老的活体宗教并非一套教义，而是一场跨越四千年的宏大对话——哲学、虔信、仪式与宇宙观交织其中——由梵、法与灵魂走向解脱的漫长旅程将其凝聚为一体。" },
  body: [
    { en: "Hinduism resists simple definition. There is no single founder, no single creed, and no central authority. It encompasses the philosophical Upanishads, the epic poems of the Mahabharata and Ramayana, the devotional hymns of the Bhakti movement, Tantric ritual traditions, and innumerable local cults. What unites this diversity is a set of shared vocabularies — Dharma (cosmic and moral order), Karma (the law of cause and consequence), Samsara (the cycle of rebirth), and the ultimate possibility of Moksha, liberation from that cycle.", zh: "印度教难以简单定义。它没有单一创始人，没有唯一信条，也没有中央权威机构。它涵盖哲学性的《奥义书》、史诗《摩诃婆罗多》与《罗摩衍那》、巴克提运动的虔信赞歌、密续仪式传统以及无数地方性崇拜。将这一多样性凝聚在一起的，是一套共同的概念框架——法（宇宙与道德秩序）、业（因果法则）、轮回（再生之循环）以及最终的解脱——从轮回中获得自由的可能。" },
    { en: "At the philosophical summit of Hinduism stands the concept of Brahman: the single, infinite, ultimate reality underlying all existence. The Upanishads, composed roughly between 800 and 200 BCE, articulate the revolutionary idea that Atman — the individual soul or self — is ultimately identical with Brahman. This equation, tat tvam asi ('that thou art'), implies that beneath the diversity of individual egos lies one undivided consciousness. The school of Advaita Vedanta, developed by the 8th-century philosopher Adi Shankaracharya, pressed this non-dual insight to its logical extreme: the apparent multiplicity of the world is maya, a kind of cosmic illusion layered over the singular real.", zh: "印度教哲学的顶峰是\"梵\"（Brahman）的概念：一切存在背后那唯一的、无限的、终极的实在。大约公元前800年至前200年间写就的《奥义书》提出了一个革命性的观念：个体灵魂——自我（Atman）——在本质上与梵同一。这一等式“汝即彼”（tat tvam asi）意味着，在诸多个体自我的多样性之下，存在着一个不可分割的意识。8世纪哲学家阿迪·商羯罗发展出不二吠檀多学派，将这一不二的洞见推向逻辑极致：世界表面上的多样性是幻象（maya），是覆盖在唯一真实之上的一种宇宙幻觉。" },
    { en: "Hinduism's religious life is richly polytheistic in practice, centered on devotion to a pantheon of deities understood as facets of a single divine reality. The Trimurti organizes three cosmic functions: Brahma the creator, Vishnu the preserver, and Shiva the destroyer and transformer. Vishnu descends to earth in avatars — Rama, Krishna, and others — when Dharma is in peril. Devi, the Great Goddess, manifests as the gentle Parvati, the fierce Durga, and the terrifying Kali, embodying the full spectrum of feminine cosmic power. Ganesha, Hanuman, Saraswati, Lakshmi, and hundreds more populate a living mythological world. Devotional worship (puja) at household shrines and massive temple complexes sustains personal relationships with these divine figures.", zh: "印度教的宗教生活在实践中呈现出丰富的多神论色彩，以对众神的虔信为核心——这些神被理解为同一神圣实在的不同侧面。三相神（Trimurti）组织了三种宇宙功能：创造之神梵天、维护之神毗湿奴与毁灭转化之神湿婆。当法（Dharma）岌岌可危时，毗湿奴会化身下凡——罗摩、克里希纳等皆为其化身。大女神（Devi）显化为温柔的帕尔瓦蒂、刚猛的难近母与令人畏惧的迦梨，体现了女性宇宙力量的全部面向。象头神迦内什、哈奴曼、辩才天女萨拉斯瓦蒂、财富女神拉克什米以及数以百计的其他神灵，构成了一个充满生命力的神话世界。在家庭神龛与宏伟神庙中的虔诚礼拜（puja）维系着信众与这些神圣存在之间的个人关系。" },
    { en: "The paths to liberation — the Yogas — are multiple, acknowledging different human temperaments. Jnana Yoga pursues liberation through discriminative knowledge and philosophical inquiry. Bhakti Yoga offers the path of intense, loving devotion to a personal deity. Karma Yoga teaches selfless action without attachment to results, as famously articulated by Krishna in the Bhagavad Gita. Raja Yoga develops the mind through meditation and the eight-limb system codified by Patanjali. These paths are not exclusive; most practitioners blend them. The Bhagavad Gita, embedded in the Mahabharata, synthesizes these strands into a conversation between the warrior Arjuna and his charioteer Krishna about duty, action, and the nature of the self.", zh: "通向解脱的道路——瑜伽（Yoga）——有多条，以适应不同的人类气质。智慧瑜伽（Jnana Yoga）通过辨别性的知识与哲学探究追求解脱；巴克提瑜伽（Bhakti Yoga）提供对人格神强烈虔诚之爱的道路；业瑜伽（Karma Yoga）教导无私行动、不执著于结果，这在《薄伽梵歌》中由克里希纳著名地阐发；胜王瑜伽（Raja Yoga）通过冥想与帕坦伽利成文的八支体系修炼心智。这些道路并不互相排斥，大多数修行者会将它们融合。《薄伽梵歌》嵌入《摩诃婆罗多》之中，以战士阿周那与御者克里希纳关于责任、行动与自我本质的对话，综合了这些脉络。" },
    { en: "The Vedic tradition divides Hindu society into four varnas (social classes) — Brahmin, Kshatriya, Vaishya, and Shudra — and prescribes ashramas, four stages of life: student, householder, forest dweller, and renunciant. The caste system has been one of Hinduism's most contested features, vigorously critiqued by reformers from the Bhakti saints to B.R. Ambedkar in the 20th century. Modern Hinduism is extraordinarily varied: it includes strict non-dualist philosophers, fervent bhaktas, practitioners of Ayurveda and Yoga as embodied disciplines, and millions who organize life around seasonal festival calendars. Hinduism's influence has spread globally through diaspora communities and the modern export of yoga, meditation, and Vedantic philosophy.", zh: "吠陀传统将印度教社会划分为四个瓦尔纳（社会阶级）——婆罗门、刹帝利、吠舍与首陀罗——并规定了四个人生阶段（ashramas）：学生期、在家期、林居期与遁世期。种姓制度是印度教最具争议的特征之一，从巴克提圣者到20世纪的安贝德卡博士，众多改革者对此提出了有力批判。现代印度教极为多元：它包括严格的不二论哲学家、热忱的虔信者、将阿育吠陀与瑜伽作为身体修炼的实践者，以及数以百万计以季节性节日历法组织生活的信众。通过散居社区以及瑜伽、冥想与吠檀多哲学的现代传播，印度教的影响已遍及全球。" },
  ],
  cards: [
    { icon: "🕉", title: { en: "Brahman", zh: "梵" }, body: { en: "The single, infinite, impersonal ground of all being. Not a deity in the Western sense, Brahman is the ultimate reality from which all existence arises and to which it returns — knowable through deep contemplation but beyond all attributes.", zh: "一切存在的唯一、无限、无人格的本体基础。梵并非西方意义上的神灵，而是一切存在由之产生、复归其中的终极实在——可通过深度沉思而知晓，却超越一切属性。" } },
    { icon: "✨", title: { en: "Atman", zh: "我（自我）" }, body: { en: "The individual self or soul. In Advaita Vedanta, Atman is ultimately non-different from Brahman; recognizing this identity is liberation itself. In dualist schools like Dvaita, Atman remains forever distinct from but lovingly dependent on God.", zh: "个体自我或灵魂。在不二吠檀多中，自我（Atman）最终与梵无异；认识到这一同一性本身即是解脱。在二元论学派如二元吠檀多中，自我永远与神明相区别，但对神充满爱意地依附。" } },
    { icon: "⚖️", title: { en: "Karma & Dharma", zh: "业与法" }, body: { en: "Karma is the moral law of cause and effect: intentional actions generate consequences that shape future lives. Dharma is the righteous order — cosmic, social, and personal — that one is called to uphold. Together they form the ethical backbone of Hindu life.", zh: "业（Karma）是因果的道德法则：有意识的行动产生影响未来生命的后果。法（Dharma）是一个人被召唤去维护的正法秩序——包括宇宙的、社会的与个人的。二者共同构成了印度教生活的伦理支柱。" } },
    { icon: "🔱", title: { en: "Shiva", zh: "湿婆" }, body: { en: "The destroyer and transformer of the Trimurti. Shiva simultaneously embodies asceticism (the Himalayan yogi) and erotic creative power (the linga). As Nataraja — lord of the cosmic dance — he dances the universe into destruction and renewal, a supreme symbol of cyclical time.", zh: "三相神中的毁灭与转化之神。湿婆同时体现苦行精神（喜马拉雅的瑜伽士）与情爱创造力（林伽）。作为那吒罗阇——宇宙舞蹈之主——他以舞蹈将宇宙带入毁灭与更新，是循环时间的至高象征。" } },
    { icon: "🪷", title: { en: "Vishnu & Avatars", zh: "毗湿奴与化身" }, body: { en: "Vishnu preserves cosmic order. When Dharma falters, he descends as an avatar. Ten principal avatars range from the fish (Matsya) and tortoise (Kurma) of primordial myth to Rama, Krishna, and — in some lists — the Buddha. The Bhagavad Gita records Krishna's teachings on duty, action, and devotion.", zh: "毗湿奴维护宇宙秩序。当法（Dharma）衰颓，他以化身降临人间。十大主要化身从原初神话中的鱼（摩蹉）与龟（俱利摩），到罗摩、克里希纳，在某些传统中还包括佛陀。《薄伽梵歌》记录了克里希纳关于责任、行动与虔信的教义。" } },
    { icon: "🌸", title: { en: "Devi — The Great Goddess", zh: "女神——大女神" }, body: { en: "Shakti is the divine feminine energy underlying all creation. Her forms span the spectrum: Saraswati (wisdom, arts), Lakshmi (prosperity, grace), Parvati (love, devotion), Durga (protection, warrior power), and Kali (time, liberation through annihilation). Shaktism venerates her as the supreme being.", zh: "夏克提（Shakti）是支撑一切创造的神圣女性能量。她的形态覆盖全部面向：辩才天女萨拉斯瓦蒂（智慧与艺术）、吉祥天女拉克什米（繁荣与恩典）、帕尔瓦蒂（爱与虔诚）、难近母杜尔迦（护佑与战士力量）以及时母迦梨（时间、通过消灭而来的解脱）。性力派将她视为最高存在。" } },
    { icon: "🧘", title: { en: "Yoga & Moksha", zh: "瑜伽与解脱" }, body: { en: "Yoga (\"union\") denotes any disciplined path linking the individual to the divine. The goal of all paths is Moksha — liberation from the cycle of birth, death, and rebirth. Achieved through knowledge, devotion, selfless action, or meditative discipline, Moksha is the final horizon of Hindu spiritual life.", zh: "瑜伽（\"结合\"）指任何将个体与神圣相连的修炼道路。所有道路的目标都是解脱（Moksha）——从生死轮回的循环中获得自由。无论通过知识、虔诚、无私行动还是禅定修炼，解脱都是印度教精神生活的最终境界。" } },
    { icon: "🐘", title: { en: "Ganesha & Living Tradition", zh: "象头神与活态传统" }, body: { en: "Ganesha — elephant-headed son of Shiva and Parvati — is the remover of obstacles and lord of beginnings, invoked before any enterprise. His ubiquity illustrates how Hinduism lives in daily life: through festivals (Diwali, Holi, Navratri), pilgrimage, life-cycle rites, and the rich texture of a tradition that has continuously evolved for four thousand years.", zh: "象头神迦内什——湿婆与帕尔瓦蒂之子——是障碍的消除者与开端之主，在任何事业开始前都会被召唤。他的无处不在展示了印度教如何活在日常生活之中：通过节日（排灯节、洒红节、九夜节）、朝圣、生命周期仪式以及这一延续四千年并持续演化的传统的丰富纹理。" } },
  ],
  questions: [
    { q: { en: "Is Hinduism monotheistic or polytheistic?", zh: "印度教是一神论还是多神论？" }, a: { en: "Both framings capture only part of the truth. Philosophically, most Hindu schools posit a single ultimate reality (Brahman or a personal God). Devotionally, practice involves many deities. One common view: the many gods are multiple faces of one reality, making Hinduism simultaneously monistic, theistic, and richly polytheistic depending on the level of analysis.", zh: "两种框架都只捕捉到了部分真相。从哲学层面看，大多数印度教学派主张存在一个终极实在（梵或人格神）。从虔信实践层面看，修行涉及众多神灵。一种常见的观点是：众多神灵是同一实在的多种面向，使得印度教根据分析层次的不同，同时呈现为一元论、有神论与丰富的多神论。" } },
    { q: { en: "What is the relationship between Atman and Brahman?", zh: "自我（Atman）与梵（Brahman）是什么关系？" }, a: { en: "This is the central question of Vedantic philosophy, with three major answers. Advaita (Shankara): Atman IS Brahman — the appearance of difference is maya. Vishishtadvaita (Ramanuja): Atman is real but is a mode of God, like a body to its soul. Dvaita (Madhva): Atman and Brahman are eternally, genuinely distinct — love across real difference is the devotional ideal.", zh: "这是吠檀多哲学的核心问题，主要有三种回答。不二吠檀多（商羯罗）：自我就是梵——差别的表象是幻象。特殊不二吠檀多（罗摩奴阇）：自我是真实的，但是神的一种样态，如同身体之于灵魂。二元吠檀多（摩陀婆）：自我与梵永远真实地相区别——在真实差异中的爱是虔信的理想。" } },
  ],
  viz: "cards",
  vizTitle: { en: "The Hindu Universe", zh: "印度教宇宙" },
  accent: "#ff8fb0",
};
export default sec;
