import type { Section } from "@/lib/types";
const sec: Section = {
  id: "life-after-death",
  num: 22,
  kicker: { en: "Section 22 · Beyond the Final Threshold", zh: "第二十二章 · 越过最后的门槛" },
  title: { en: "Life After Death", zh: "死后世界" },
  lead: { en: "Every human civilization has grappled with death and what — if anything — lies beyond it. The answers cultures have imagined range from eternal paradise to perpetual rebirth, from ancestral spirit realms to simple dissolution into the natural world.", zh: "每一种人类文明都曾面对死亡，以及死后——若有的话——究竟存在什么。各文化所想象的答案，从永恒天堂到无尽轮回，从祖先灵界到回归自然，无所不包。" },
  body: [
    { en: "The universality of afterlife belief is one of the most striking facts about human culture. Archaeological evidence — grave goods, burial orientation, ochre pigments marking the dead — suggests that even Neanderthals and early Homo sapiens marked death as a threshold rather than an endpoint. Anthropologist Pascal Boyer argues that afterlife beliefs emerge naturally from cognitive tendencies: our 'agent detection' systems and our difficulty imagining total non-existence predispose us to model the dead as continuing in some form.", zh: "来世信仰的普遍性是人类文化最引人注目的事实之一。考古证据——陪葬品、墓葬朝向、标记亡者的赭石颜料——表明，甚至尼安德特人和早期智人就已将死亡视为门槛而非终点。人类学家帕斯卡尔·博耶认为，来世信仰自然地源于认知倾向：我们的“主体探测”系统以及难以想象彻底虚无的本能，使我们倾向于将死者视为以某种形式延续存在。" },
    { en: "The Abrahamic religions — Judaism, Christianity, and Islam — broadly share a framework of individual resurrection or immortal soul, divine judgment, and differentiated destinations: paradise or reward for the righteous, and punishment or separation from God for the wicked. Details differ significantly: mainstream Judaism historically focused more on communal life than personal afterlife; Christianity developed elaborate theologies of heaven, hell, and purgatory; Islam describes the afterlife (akhira) in vivid and detailed terms, with the Garden (Jannah) and the Fire (Jahannam) as primary destinations determined by earthly deeds and faith.", zh: "亚伯拉罕诸宗教——犹太教、基督教与伊斯兰教——大体上共享一个框架：个体复活或不死灵魂、神圣审判，以及分化的归宿：义人的天堂或奖赏，邪恶者的惩罚或与神的隔绝。细节差异显著：主流犹太教历来更关注群体生活而非个人来世；基督教发展出了关于天堂、地狱与炼狱的精密神学；伊斯兰教以生动详细的语言描述来世（ākhira），以花园（真主乐园）与烈火（火狱）作为由今生行为与信仰所决定的主要归宿。" },
    { en: "South Asian traditions offer distinct cosmologies. In Hinduism, the individual self (Atman) is immortal and undergoes reincarnation across countless lives, driven by the moral law of karma. Liberation (moksha) is release from this cycle — the merging of Atman into Brahman, the universal ground of being. Buddhism, while rejecting a permanent, fixed self, still teaches that a continuum of consciousness is reborn according to karma until nirvana — the cessation of craving and suffering — is achieved. The Tibetan Buddhist tradition offers particularly detailed accounts of the intermediate state (bardo) between death and rebirth, elaborated in the Bardo Thodol (Tibetan Book of the Dead).", zh: "南亚传统提供了独特的宇宙观。在印度教中，个体自我（阿特曼）是不朽的，在业力法则的驱动下经历无数次轮回。解脱（莫克夏）是从这一循环中解脱出来——阿特曼融入梵（存在的宇宙根基）。佛教虽否认永久固定的自我，但仍教导意识流根据业力不断再生，直至涅槃——贪欲与苦难的止息——得以实现。藏传佛教传统提供了关于死亡与再生之间中阴（中有）状态的特别详尽描述，见于《西藏度亡经》（中阴得度）。" },
    { en: "Ancient Egypt developed one of history's most elaborate mortuary cultures. The dead faced judgment in the Hall of Two Truths, where the heart was weighed against the feather of Ma'at (truth and justice). The worthy entered the Field of Reeds (Aaru), an idealized version of Egypt, while the unworthy were devoured by the monster Ammit. Preservation of the body through mummification was essential because the Ka (life force) and Ba (personality soul) needed the physical form as an anchor. Elaborate funerary texts — the Book of the Dead, Pyramid Texts — were designed to guide and protect the deceased through the journey.", zh: "古埃及发展出了历史上最为繁复的丧葬文化之一。亡者须在双真理厅接受审判，心脏与代表真理与正义的玛阿特之羽相衡。品行端正者进入芦苇之野（Aaru）——一个理想化的埃及世界，品行不端者则被怪兽阿米特吞噬。通过木乃伊化保存肉身至关重要，因为卡（生命力）与巴（人格灵魂）需要物理形态作为锚定。精心制作的丧葬文本——《亡灵书》、《金字塔铭文》——旨在引导并保护亡者度过旅途。" },
    { en: "From a naturalistic or scientific standpoint, consciousness is a product of brain processes, and death — the cessation of those processes — entails the permanent end of subjective experience. There is no verified scientific evidence for survival of consciousness after death. Near-death experiences (NDEs), studied by researchers such as Raymond Moody and Pim van Lommel, are frequently cited as suggestive of something beyond death; however, most neuroscientists attribute them to physiological processes in the dying brain: oxygen deprivation, REM intrusion, surges of neural activity. The naturalistic view counsels finding meaning in the finite span of life rather than deferring it to an imagined hereafter.", zh: "从自然主义或科学的角度来看，意识是大脑过程的产物，死亡——这些过程的停止——意味着主观体验的永久终结。目前没有经过验证的科学证据支持死后意识的存续。濒死体验（NDE）——由雷蒙德·穆迪、彼姆·范·洛梅尔等研究者研究——常被引用为死后存在某种东西的暗示；然而，大多数神经科学家将其归因于濒死大脑中的生理过程：缺氧、快速眼动期入侵、神经活动的激增。自然主义观点主张在有限的生命中寻找意义，而非将其推迟至想象中的来世。" },
  ],
  cards: [
    { icon: "✝️", title: { en: "Christian Heaven & Hell", zh: "基督教的天堂与地狱" }, body: { en: "Christianity teaches bodily resurrection, final judgment, and eternal destinations: heaven (communion with God), hell (eternal separation or punishment), and in Catholic tradition, purgatory (purification before heaven). Views on hell range from eternal conscious torment to annihilationism.", zh: "基督教教导肉身复活、末日审判与永恒归宿：天堂（与神的共融）、地狱（永恒隔绝或惩罚），以及在天主教传统中的炼狱（进天堂前的净化）。关于地狱的观点从永恒有意识的折磨到灭绝论不等。" } },
    { icon: "☪️", title: { en: "Islamic Akhira", zh: "伊斯兰教的来世" }, body: { en: "In Islam, after death comes the barzakh (intermediate state), then resurrection on the Day of Judgment. The righteous enter Jannah (paradise), described with rivers, gardens, and divine presence; the wicked enter Jahannam (hellfire). Deeds, faith, and divine mercy all factor into judgment.", zh: "在伊斯兰教中，死后进入中间状态（中阴界），然后在审判日复活。义人进入真主乐园（天园），其中有河流、花园与神圣同在；邪恶者进入火狱。行为、信仰与神恩都是审判的因素。" } },
    { icon: "🕉️", title: { en: "Hindu Reincarnation & Moksha", zh: "印度教的轮回与解脱" }, body: { en: "Hinduism teaches that the immortal Atman undergoes samsara — the cycle of rebirth — across many lives and forms, shaped by karma (accumulated moral action). Liberation (moksha) frees the Atman from this cycle, reuniting it with Brahman, the ultimate reality.", zh: "印度教教导不朽的阿特曼经历轮回——跨越许多生命与形态的再生循环——由业力（积累的道德行为）塑造。解脱（莫克夏）使阿特曼从这一循环中解脱，与梵——终极实在——重新合一。" } },
    { icon: "☸️", title: { en: "Buddhist Rebirth & Nirvana", zh: "佛教的再生与涅槃" }, body: { en: "Buddhism teaches that a stream of consciousness continues after death, shaped by karma, and is reborn until nirvana is achieved. Tibetan Buddhism details the bardo — an intermediate state offering opportunities for liberation. Nirvana is not annihilation but the cessation of craving and the end of suffering.", zh: "佛教教导意识流在死后延续，受业力塑造，不断再生直至涅槃实现。藏传佛教详细描述了中阴——一个提供解脱机会的中间状态。涅槃并非消灭，而是贪欲的止息与苦难的终结。" } },
    { icon: "𓂀", title: { en: "Ancient Egyptian Afterlife", zh: "古埃及来世" }, body: { en: "The dead underwent judgment in the Hall of Two Truths: hearts weighed against the feather of Ma'at. The worthy entered the Field of Reeds. Mummification preserved the body for the Ka and Ba. Funerary texts (Book of the Dead) guided the soul through dangerous terrain toward eternal life.", zh: "亡者在双真理厅接受审判：心脏与玛阿特之羽相衡。品行端正者进入芦苇之野。木乃伊化保存肉身以供卡与巴使用。丧葬文本（《亡灵书》）引导灵魂穿越险途，走向永恒生命。" } },
    { icon: "🔬", title: { en: "Naturalism: Death as Ending", zh: "自然主义：死亡即终结" }, body: { en: "The scientific consensus holds that consciousness is generated by the brain, so death ends subjective experience permanently. Near-death experiences are explained as physiological events in the dying brain. Meaning is found in finite life, relationships, and contribution — not in a projected hereafter.", zh: "科学共识认为意识由大脑产生，因此死亡永久终结主观体验。濒死体验被解释为濒死大脑中的生理事件。意义在有限的生命、人际关系与贡献中寻得——而非寄托于想象的来世。" } },
  ],
  viz: "comparison",
  vizTitle: { en: "What Happens After Death", zh: "死后会发生什么" },
  comparison: {
    aspect: { en: "What happens after death", zh: "死后发生什么" },
    dimensions: [
      { en: "Christianity", zh: "基督教" },
      { en: "Islam", zh: "伊斯兰教" },
      { en: "Hinduism", zh: "印度教" },
      { en: "Buddhism", zh: "佛教" },
      { en: "Ancient Egypt", zh: "古埃及" },
      { en: "Naturalism", zh: "自然主义" },
    ],
    cells: [
      { en: "The soul faces divine judgment; the righteous are resurrected to heaven (eternal communion with God) and the wicked consigned to hell or annihilation. Catholic tradition adds purgatory as a stage of purification. Final bodily resurrection unites soul and body at the end of history.", zh: "灵魂接受神圣审判；义人复活进入天堂（与神的永恒共融），邪恶者被打入地狱或湮灭。天主教传统在此之外增设炼狱作为净化阶段。历史终结时，肉身的最终复活使灵魂与肉体重新结合。" },
      { en: "After death, the soul enters barzakh (an intermediate state in the grave) until the Day of Judgment. All are then resurrected for divine reckoning: the faithful and righteous enter Jannah (paradise with rivers, gardens, and divine presence), while the unrighteous face Jahannam (hellfire), with the possibility of divine mercy.", zh: "死后，灵魂进入中阴界（墓中的中间状态），直至审判日。届时所有人复活接受神圣清算：信仰虔诚、行为端正者进入真主乐园（有河流、花园与神圣同在），不义者面临火狱，但神恩仍有可能降临。" },
      { en: "The immortal Atman leaves the body and, according to accumulated karma, is reborn into a new life — human, animal, or divine. This cycle of samsara continues until the soul attains moksha: liberation from rebirth through knowledge, devotion, or right action, merging back into Brahman, the universal self.", zh: "不朽的阿特曼离开肉身，依据积累的业力，再生为新的生命——人、动物或神灵。这一轮回循环持续，直至灵魂通过知识、虔诚或正当行为获得解脱（莫克夏）：从轮回中解放，融入梵——宇宙自我。" },
      { en: "A stream of consciousness continues after death, not as a fixed soul but as a karmic continuum. It is reborn in one of six realms (gods, demigods, humans, animals, hungry ghosts, hell beings) according to karma. The goal is nirvana: the extinction of craving and ignorance, ending rebirth entirely. Tibetan Buddhism describes a detailed bardo (intermediate state) between death and rebirth.", zh: "意识流在死后延续，不是固定的灵魂，而是业力的相续。依据业力，在六道（天、阿修罗、人、动物、饿鬼、地狱众生）之一中再生。目标是涅槃：贪欲与无明的熄灭，彻底终结轮回。藏传佛教详细描述了死亡与再生之间的中阴（中间状态）。" },
      { en: "After death, the heart is weighed against the feather of Ma'at in the Hall of Two Truths. The worthy enter the Field of Reeds (Aaru), an eternal paradise mirroring Egypt. The unworthy are devoured by Ammit. The Ka and Ba require the preserved body (mummification) as an anchor; funerary texts navigate the dangerous journey to eternal life.", zh: "死后，心脏在双真理厅与玛阿特之羽相衡。品行端正者进入芦苇之野（Aaru）——一个映射埃及的永恒乐园。品行不端者被阿米特吞噬。卡与巴需要保存完好的肉身（木乃伊化）作为锚点；丧葬文本引导亡者安全度过通往永恒生命的险途。" },
      { en: "Consciousness is produced by brain activity; death permanently ends subjective experience. There is no empirical evidence for survival after death. Near-death experiences reflect neurological processes in the dying brain. Meaning, value, and legacy are found entirely within finite life — in relationships, creativity, and contribution to the living world.", zh: "意识由大脑活动产生；死亡永久终结主观体验。没有经验证据支持死后意识的存续。濒死体验反映的是濒死大脑中的神经过程。意义、价值与遗产完全在有限的生命中寻得——在人际关系、创造力与对生者世界的贡献之中。" },
    ],
  },
  accent: "#74b6e6",
};
export default sec;
