import type { Section } from "@/lib/types";
const sec: Section = {
  id: "enlightenment",
  num: 24,
  kicker: { en: "Section 24 · The Great Awakening", zh: "第二十四章 · 大觉" },
  title: { en: "Enlightenment", zh: "觉悟" },
  lead: { en: "Across the world's contemplative traditions, a single possibility recurs: that ordinary human consciousness can undergo a radical transformation — a clearing so complete that suffering, delusion, and the sense of a separate self are seen through, and what remains is described, haltingly, as freedom.", zh: "在世界各大沉思传统中，一种可能性反复出现：普通人类意识能够经历一次根本性的转化——彻底的澄明，令苦难、迷妄与孤立自我的幻象悉数消融，剩余之物被人们战战兢兢地称为——自由。" },
  body: [
    { en: "The word 'enlightenment' is a modern Western coinage, reaching for several distinct but family-resembling concepts: the Buddhist bodhi (awakening, as in the Bodhi tree under which Siddhartha sat), nirvana (the extinguishing of craving and the cessation of rebirth), the Hindu moksha (liberation from the cycle of samsara), and the mystical union sought in Sufi, Christian, and Jewish esoteric traditions. Each tradition insists its path is unique; anthropologists note the structural similarities.", zh: "「觉悟」一词是现代西方的造语，指向若干彼此不同却同属一家的概念：佛教的「菩提」（悉达多菩提树下的觉醒）、「涅槃」（熄灭贪欲与轮回的止息）、印度教的「解脱」（从轮回中得自由），以及苏菲、基督教与犹太神秘主义传统所追求的神秘合一。每个传统都坚称自身道路独一无二；人类学家则注意到其结构上的深层相似。" },
    { en: "Buddhism, in its many schools, frames enlightenment as the direct experiential recognition of three marks of existence: impermanence (anicca), unsatisfactoriness (dukkha), and no-self (anatta). Theravada Buddhism describes nirvana as the unconditional — beyond birth and death, beyond conceptual description. Mahayana schools add the bodhisattva ideal: delaying full awakening out of compassion for all sentient beings. Zen points to sudden insight (satori); Tibetan Vajrayana speaks of rigpa, naked awareness itself.", zh: "佛教各宗派将觉悟理解为对三种存在特质的直接体验性认识：无常（anicca）、苦（dukkha）、无我（anatta）。上座部佛教将涅槃描述为无条件者——超越生死，超越概念表述。大乘诸宗则添入菩萨理想：出于对一切有情众生的悲悯，暂缓完全觉悟。禅宗指向顿悟（satori）；藏传金刚乘则言说「本觉」（rigpa），即赤裸的觉知本身。" },
    { en: "Hindu traditions frame liberation as moksha — the recognition that the individual self (Atman) is identical to ultimate reality (Brahman). This is not annihilation but the falling away of a false identification, like a wave realizing it is ocean. Advaita Vedanta, the non-dual school associated with Adi Shankaracharya, holds that only Brahman is real; the apparent multiplicity of the world is maya — a cosmic overlay that enlightenment dissolves. Bhakti traditions approach the same terrain through devotional love: the lover merges in the beloved.", zh: "印度教各传统将解脱理解为「莫克沙」——认识到个体自我（Atman）与终极实在（梵，Brahman）同一无别。这不是湮灭，而是虚假认同的脱落，如同波浪意识到自己就是海洋。与商羯罗相关的不二论（Advaita Vedanta）认为唯有梵是真实的；世界表象的多样性是「摩耶」（maya）——一层被觉悟所穿透的宇宙幕帘。虔信传统则通过奉爱之情趋近同一境界：爱者融入所爱之中。" },
    { en: "In Taoism, liberation is less a dramatic awakening than a continuous, deepening alignment with the Tao — the unnameable, generative ground of all things. The sage (zhenren, 真人) is not someone who has arrived but someone who moves without obstruction, like water finding its level. Zhuangzi's stories subvert the very desire for enlightenment: the butterfly dream does not resolve whether Zhuangzi became a butterfly or the butterfly dreamed it was Zhuangzi — and that unresolvability is the point.", zh: "在道家思想中，解脱与其说是一次戏剧性的觉醒，不如说是与「道」——一切万物不可名状的生发之基——持续深化的契合。圣人（真人）不是已抵达终点之人，而是行无阻碍之人，如水之就下。庄子的故事颠覆了对觉悟本身的渴求：蝴蝶梦并不解决庄周梦蝶还是蝶梦庄周的问题——那无法解决，正是其意义所在。" },
    { en: "Mystical traditions within theistic religions describe enlightenment as union with God — not merger that erases the self but an intimacy so total that the boundary between lover and beloved becomes translucent. Meister Eckhart spoke of the birth of God in the soul; al-Hallaj declared 'I am the Truth' and was executed for it; the Kabbalists mapped the soul's ascent through the sefirotic tree. What unites these accounts is the reversal of ordinary subject-object consciousness — not the world apprehended by a self, but awareness prior to the division.", zh: "有神论宗教内部的神秘主义传统将觉悟描述为与神的合一——不是湮没自我的融合，而是一种如此彻底的亲密，以至于爱者与所爱之间的界限变得透明。埃克哈特大师谈论神在灵魂中的诞生；哈拉智宣称「我即真理」而身遭杀戮；卡巴拉学者则描绘灵魂经由质点树的升华。这些叙述的共同点是对普通主客体意识的颠覆——不是被一个自我所把握的世界，而是先于此分裂的觉知本身。" },
  ],
  cards: [
    { icon: "🌳", title: { en: "Bodhi (Buddhism)", zh: "菩提（佛教）" }, body: { en: "Awakening to the nature of mind — the direct seeing through impermanence, suffering, and the illusion of a fixed self. The historical Buddha attained bodhi under the Bodhi tree at Bodh Gaya.", zh: "对心性的觉醒——直接看穿无常、苦与固定自我之幻象。历史上的佛陀在菩提伽耶的菩提树下证得菩提。" } },
    { icon: "🕯️", title: { en: "Nirvana (Buddhism)", zh: "涅槃（佛教）" }, body: { en: "The extinguishing of craving, aversion, and delusion — and with them, the fuel for rebirth. Described as the unconditioned, it is often said the Buddha refused to characterize it as existence or non-existence.", zh: "熄灭贪、嗔、痴——以及由此驱动的轮回之燃料。涅槃被描述为无条件者；据载佛陀拒绝将其定性为存在或非存在。" } },
    { icon: "🔥", title: { en: "Moksha (Hinduism)", zh: "解脱（印度教）" }, body: { en: "Liberation from the cycle of samsara — the recognition that Atman (individual self) and Brahman (ultimate reality) are non-dual. Approached through jnana (knowledge), bhakti (devotion), karma (action), or raja (meditation) yoga.", zh: "从轮回中解脱——认识到个体自我（Atman）与终极实在（梵）不二。可经由智慧瑜伽、虔信瑜伽、行动瑜伽或王瑜伽趋近。" } },
    { icon: "☯️", title: { en: "Alignment with Tao (Taoism)", zh: "与道合一（道家）" }, body: { en: "The Taoist sage does not 'achieve' liberation but dissolves the effort-self that blocks natural flow. Wu wei — non-forcing action — is not passivity but action without the friction of ego-agenda.", zh: "道家圣人不是「成就」解脱，而是消融阻断自然流动的努力之自我。「无为」并非被动，而是没有自我意图之摩擦的行动。" } },
    { icon: "✨", title: { en: "Mystical Union (Theistic traditions)", zh: "神秘合一（有神论传统）" }, body: { en: "Sufi fana (annihilation of the ego in God), Christian theosis (deification), Kabbalistic devekut (cleaving to God) — all describe a shift from relating to the divine to being permeated by it.", zh: "苏菲的「消融」（自我在神中的湮没）、基督教的「神化」（theosis）、卡巴拉的「附着」（devekut，与神合一）——皆描述一种从与神相关转变为被神贯穿的转化。" } },
    { icon: "⚡", title: { en: "Satori / Kensho (Zen)", zh: "悟（禅宗）" }, body: { en: "A sudden glimpse of one's original nature — not an intellectual conclusion but an experiential jolt that cannot be argued into or out of. Koans (paradoxical riddles) are tools for precipitating this breakthrough.", zh: "对本来面目的忽然一瞥——不是智识上的结论，而是无法被论证进出的体验性震撼。公案（悖论性谜题）是催化这一突破的工具。" } },
    { icon: "💎", title: { en: "Rigpa (Tibetan Vajrayana)", zh: "本觉（藏传金刚乘）" }, body: { en: "Naked, unmodified awareness — the ground of mind not obscured by conceptual overlay. Dzogchen and Mahamudra point to this as the always-already-present nature of consciousness, never lost, only unrecognized.", zh: "赤裸、未经修饰的觉知——未被概念遮蔽的心之基础。大圆满与大手印指向此为意识从来如此、从未失去、只是未被认识的本性。" } },
    { icon: "🌊", title: { en: "Non-Dual Recognition (Advaita)", zh: "非二元认识（不二论）" }, body: { en: "The Advaita Vedanta teaching that Brahman alone is real — all apparent multiplicity arises in and is not separate from that one awareness. Enlightenment is the falling away of the mistaken sense of being a separate observer.", zh: "不二论吠檀多的教义：唯有梵是真实的——一切表象上的多样性皆生于那一觉知，且不与之分离。觉悟是错误地将自身视为独立观察者这一感受的脱落。" } },
  ],
  questions: [
    { q: { en: "Is enlightenment a permanent state or a series of deepening insights?", zh: "觉悟是一种永久的状态，还是一系列不断深化的洞见？" }, a: { en: "Traditions disagree sharply. Zen speaks of 'sudden enlightenment, gradual cultivation.' Advaita often describes it as instantaneous recognition that cannot be undone. Most teachers acknowledge that peak insights must be integrated into ordinary life — the 'after enlightenment, chop wood, carry water' wisdom.", zh: "各传统在此存在明显分歧。禅宗言「顿悟渐修」；不二论则通常将其描述为一种无法被撤销的瞬间认识。大多数导师承认，洞见的高峰必须融入日常生活——「悟后劈柴担水」的智慧。" } },
    { q: { en: "Can enlightenment be verified from the outside?", zh: "觉悟能从外部加以验证吗？" }, a: { en: "This is one of the deepest problems in comparative mysticism. Teacher lineages often use behavioral markers — compassion, equanimity, freedom from compulsive reactivity — but these are not definitive. The tradition of 'dharma combat' in Zen attempts a dialogical test. Neuroscience can measure correlates of meditative states but cannot confirm their ultimate nature.", zh: "这是比较神秘主义中最深层的难题之一。传承中的导师通常使用行为标志——悲悯、平静、免于强迫性反应——但这些并非决定性的。禅宗的「法战」传统试图进行对话性检验。神经科学可以测量冥想状态的关联指标，但无法确认其终极本性。" } },
  ],
  viz: "comparison",
  vizTitle: { en: "Four Paths to Liberation", zh: "四条解脱之路" },
  comparison: {
    aspect: { en: "What awakening/liberation means in this tradition", zh: "该传统中觉醒／解脱的含义" },
    dimensions: [
      { en: "Buddhism (Nirvana / Bodhi)", zh: "佛教（涅槃／菩提）" },
      { en: "Hinduism (Moksha)", zh: "印度教（解脱）" },
      { en: "Taoism (Union with the Tao)", zh: "道家（与道合一）" },
      { en: "Mystical Union (Theistic traditions)", zh: "神秘合一（有神论传统）" },
    ],
    cells: [
      { en: "The extinguishing of craving and the direct seeing of impermanence, suffering, and no-self. For Theravada, nirvana is the unconditioned — beyond all description. For Mahayana, full enlightenment (bodhi) includes boundless compassion for all beings.", zh: "熄灭贪欲，直接看见无常、苦与无我。上座部佛教中，涅槃是无条件者——超越一切描述。大乘佛教中，圆满觉悟（菩提）还包括对一切众生无边的悲悯。" },
      { en: "The recognition that the individual self (Atman) is non-dual with ultimate reality (Brahman). Not annihilation, but the dissolution of mistaken identification. Approached via four yogas: knowledge, devotion, selfless action, and meditation.", zh: "认识到个体自我（Atman）与终极实在（梵）不二无别。不是湮灭，而是错误认同的消融。可经由四种瑜伽路径趋近：智识、奉爱、无私行动与冥想。" },
      { en: "Not a single dramatic event but an ongoing, deepening naturalness — moving in harmony with the Tao without forcing. The sage sheds the artificial self and acts with the spontaneous effortlessness of water or bamboo in wind.", zh: "不是单一的戏剧性事件，而是持续深化的自然性——无强迫地与道谐动。圣人卸去人为的自我，以水或风中竹的自然无为而行。" },
      { en: "The soul's union with God — not absorption into an impersonal absolute, but an intimate permeation in which the distinction between self and divine becomes translucent without fully disappearing. Called fana (Sufism), theosis (Christianity), or devekut (Kabbalah).", zh: "灵魂与神的合一——不是被非人格的绝对所吸收，而是一种亲密的贯穿，其中自我与神圣之间的界限变得透明，却不完全消失。称为「消融」（苏菲主义）、「神化」（基督教）或「附着」（卡巴拉）。" },
    ],
  },
  quote: { text: { en: "\"Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.\"", zh: "「悟前劈柴担水，悟后劈柴担水。」" }, attr: { en: "— Zen proverb", zh: "— 禅宗谚语" } },
  accent: "#a489ff",
};
export default sec;
