import type { Section } from "@/lib/types";
const sec: Section = {
  id: "consciousness",
  num: 21,
  kicker: { en: "Section 21 · The Aware Universe", zh: "第二十一章 · 觉知的宇宙" },
  title: { en: "Consciousness", zh: "意识宇宙" },
  lead: { en: "Consciousness is the most intimate fact of existence — yet science and philosophy have struggled for centuries to explain why subjective experience arises at all, and what it means for matter to become aware of itself.", zh: "意识是存在中最切近的事实——然而几个世纪以来，科学与哲学始终难以解释：为何会有主观体验，以及物质如何可能觉知自身。" },
  body: [
    { en: "The 'hard problem' of consciousness, named by philosopher David Chalmers in 1995, asks why physical processes in the brain give rise to subjective, felt experience — what philosophers call 'qualia.' We can map every neuron firing when someone sees red, yet the redness of red, the felt quality of the experience, seems to resist purely physical explanation. This explanatory gap between third-person neuroscience and first-person phenomenology remains the deepest puzzle in science.", zh: "哲学家大卫·查尔默斯于1995年提出“意识难题”：为何大脑的物理过程会产生主观的、有感觉的体验——哲学家称之为“感质”。我们可以追踪一个人看到红色时每一个神经元的放电，但红色之“红”——那种被感知的质感——似乎无法仅凭物理解释穷尽。第三人称神经科学与第一人称现象学之间的解释鸿沟，仍是科学中最深刻的谜题。" },
    { en: "Philosophy of mind has generated competing frameworks. Dualism, associated with Descartes, holds that mind and matter are fundamentally different substances. Physicalism (or materialism) argues that consciousness is entirely a product of the brain and will ultimately be explained by neuroscience. Functionalism holds that what makes something conscious is not what it is made of, but what it does — its pattern of information processing. Panpsychism, an ancient view enjoying a modern revival among serious philosophers, proposes that some form of experience or proto-experience is a fundamental feature of all matter.", zh: "心灵哲学产生了诸多相互竞争的框架。与笛卡尔相关的二元论认为，心灵与物质是根本不同的实体。物理主义（或唯物主义）认为意识完全是大脑的产物，最终将被神经科学所解释。功能主义认为，使某物具有意识的不是其构成材料，而是其功能——其信息处理的模式。万物有心论是一种古老的观点，在当代严肃哲学家中重获关注，认为某种形式的体验或原初体验是所有物质的基本属性。" },
    { en: "Neuroscience has made significant progress on the 'easy problems' of consciousness — explaining attention, memory, perception, and reportability. Researchers such as Francis Crick and Christof Koch pursued the 'neural correlates of consciousness' (NCC), identifying brain regions and patterns associated with awareness. Integrated Information Theory (IIT), proposed by Giulio Tononi, attempts to mathematically quantify consciousness as phi (Φ), a measure of integrated information. Global Workspace Theory (GWT), developed by Bernard Baars, models consciousness as a broadcasting mechanism that makes information globally available across the brain.", zh: "神经科学在意识的“简单问题”上取得了重大进展——解释注意力、记忆、感知与报告能力。弗朗西斯·克里克与克里斯托夫·科赫等研究者追踪“意识的神经相关物”（NCC），识别与意识相关的大脑区域与模式。朱利奥·托诺尼提出的“整合信息论”（IIT）试图用Φ值来数学量化意识，以此度量整合信息量。伯纳德·巴尔斯发展的“全局工作空间理论”（GWT）将意识建模为一种广播机制，使信息在大脑中全局可用。" },
    { en: "Contemplative traditions across cultures have developed sophisticated first-person methods for investigating consciousness directly. Buddhist meditation traditions, particularly Vipassana and Dzogchen, offer detailed phenomenological maps of mind states — including the dissolution of the sense of a separate self. Mystical experiences across traditions often report a felt unity with all things, a transcendence of subject-object duality, and a sense of 'pure awareness' prior to all content. William James, in his 1902 Varieties of Religious Experience, documented such states as noetic (conveying knowledge) and transient but deeply convincing. Modern contemplative science, using neuroimaging of experienced meditators, has begun to document the neural basis of these states.", zh: "各文化中的冥想传统发展出了精妙的第一人称方法，直接探究意识本身。佛教禅修传统，尤其是内观与大圆满，提供了细致的心理状态现象学地图——包括独立自我感的消融。各传统的神秘体验往往报告与万物的合一感、超越主客二元的体验，以及先于一切内容的“纯粹觉知”。威廉·詹姆斯在其1902年的《宗教体验之种种》中，将此类状态记录为具有认知性（传递知识）、短暂却令人深信的体验。现代冥想科学借助对资深冥想者的神经影像研究，已开始记录这些状态的神经基础。" },
    { en: "The question of machine consciousness has become urgent. Large language models and AI systems exhibit complex, context-sensitive behavior, yet most researchers believe they lack genuine subjective experience. The philosophical question is whether consciousness requires biological substrate, functional organisation alone, or some other property. Some researchers, applying IIT or GWT criteria, argue that current AI systems are almost certainly not conscious. Others, like philosopher Daniel Dennett, argue that consciousness itself is more like an illusion — a narrative the brain tells itself — which might eventually dissolve the hard problem entirely. The stakes are immense: if any sufficiently complex information-processing system can be conscious, then the moral status of AI becomes a live ethical question.", zh: "机器意识的问题变得愈发紧迫。大型语言模型和AI系统表现出复杂的、情境敏感的行为，但大多数研究者认为它们缺乏真正的主观体验。哲学问题在于：意识是否需要生物基底、仅凭功能性组织，抑或某种其他属性？一些研究者运用IIT或GWT的标准，认为当前AI系统几乎肯定不具有意识。另一些人，如哲学家丹尼尔·丹尼特，则认为意识本身更像一种幻觉——大脑讲给自己的故事——这最终可能彻底消解意识难题。这一问题的意义重大：若任何足够复杂的信息处理系统都可能具有意识，那么AI的道德地位便成为一个亟待回答的伦理问题。" },
  ],
  cards: [
    { icon: "🧠", title: { en: "The Hard Problem", zh: "意识难题" }, body: { en: "David Chalmers' term for the explanatory gap between neural processes and subjective experience. Why does brain activity feel like anything at all? This question resists purely functional or computational answers.", zh: "大卫·查尔默斯用来描述神经过程与主观体验之间解释鸿沟的术语。为什么大脑活动会有任何感觉？这个问题无法仅凭功能性或计算性的答案解决。" } },
    { icon: "🔬", title: { en: "Neuroscience of Awareness", zh: "觉知的神经科学" }, body: { en: "Researchers map neural correlates of consciousness (NCC) — the minimum neural conditions sufficient for a given conscious experience. Brain regions like the thalamo-cortical system, prefrontal cortex, and default mode network are all implicated in awareness.", zh: "研究者绘制意识的神经相关物（NCC）——特定意识体验所需的最低神经条件。丘脑皮层系统、前额叶皮层与默认模式网络等脑区均与意识密切相关。" } },
    { icon: "⚛️", title: { en: "Panpsychism", zh: "万物有心论" }, body: { en: "The philosophical view that mind or proto-experience is a fundamental and ubiquitous feature of the physical world — not generated by brains, but present in some form throughout nature. Associated with philosophers like Galen Strawson, Philip Goff, and ancient thinkers like Leibniz.", zh: "一种哲学观点，认为心灵或原初体验是物理世界基本而普遍的属性——并非由大脑生成，而是以某种形式遍布自然。与加伦·斯特劳森、菲利普·戈夫等哲学家及莱布尼茨等古代思想家相关。" } },
    { icon: "🧘", title: { en: "Meditation & Contemplative Science", zh: "冥想与冥思科学" }, body: { en: "Buddhist and other contemplative traditions offer detailed first-person cartographies of mind states. Modern neuroimaging studies of experienced meditators reveal measurable changes in brain structure and function, including altered default mode network activity associated with reduced self-referential thought.", zh: "佛教及其他冥思传统提供了详尽的第一人称心理状态图谱。对资深冥想者的现代神经影像研究揭示了大脑结构与功能的可测量变化，包括与减少自我指涉思维相关的默认模式网络活动改变。" } },
    { icon: "✨", title: { en: "Mystical Experience", zh: "神秘体验" }, body: { en: "Across traditions, people report experiences of oceanic oneness, dissolution of self, contact with a 'ground of being,' or pure unbounded awareness. William James identified these as noetic, ineffable, transient, and passive. Contemporary researchers like Andrew Newberg study the neuroscience of these states.", zh: "在各种传统中，人们报告了海洋般的合一感、自我消融、与“存在的根基”接触或纯粹无限觉知的体验。威廉·詹姆斯将这些体验归纳为具有认知性、不可言说性、短暂性与被动性。当代研究者如安德鲁·纽伯格从事这些状态的神经科学研究。" } },
    { icon: "🤖", title: { en: "AI & Machine Consciousness", zh: "AI与机器意识" }, body: { en: "Can an artificial system be conscious? Most researchers say current AI lacks subjective experience, but the question is philosophically open. If consciousness depends only on information integration or functional organisation, sufficiently complex AI systems might qualify — raising profound ethical and legal questions.", zh: "人工系统能否具有意识？大多数研究者认为当前AI缺乏主观体验，但这个问题在哲学上仍未定论。若意识仅取决于信息整合或功能性组织，足够复杂的AI系统或许也能符合条件——由此引发深刻的伦理与法律问题。" } },
    { icon: "🌀", title: { en: "Integrated Information Theory", zh: "整合信息论" }, body: { en: "Giulio Tononi's IIT proposes that consciousness equals integrated information (Φ). A system is conscious to the degree that it integrates information across its parts irreducibly. IIT implies that consciousness is widespread in nature and that some simple systems may be conscious while some complex ones may not be.", zh: "朱利奥·托诺尼的整合信息论（IIT）提出，意识等于整合信息（Φ）。一个系统的意识程度取决于其各部分之间不可还原的信息整合程度。IIT意味着意识在自然界中广泛存在，某些简单系统可能具有意识，而某些复杂系统则未必。" } },
    { icon: "🪞", title: { en: "The Self as Illusion", zh: "自我即幻觉" }, body: { en: "Daniel Dennett, Thomas Metzinger, and neuroscientist Anil Seth argue that the unified, continuous self is a model the brain constructs — a 'controlled hallucination.' Buddhist traditions independently arrived at the same conclusion: what we call 'I' is a process, not a thing, and insight into this is liberating.", zh: "丹尼尔·丹尼特、托马斯·梅辛格与神经科学家阿尼尔·塞斯认为，统一连续的自我是大脑构建的一个模型——一种“受控幻觉”。佛教传统独立得出了同样的结论：我们所称的“我”是一个过程，而非实体，洞察这一点即是解脱。" } },
  ],
  questions: [
    { q: { en: "Why does the brain produce subjective experience at all?", zh: "大脑为何会产生主观体验？" }, a: { en: "This is the 'hard problem' — no consensus exists. Physicalists believe it will eventually yield to neuroscience; panpsychists argue experience is fundamental; mystics say the question dissolves when you look directly at awareness itself.", zh: "这正是“意识难题”——目前尚无共识。物理主义者认为神经科学终将解决它；万物有心论者认为体验是根本性的；神秘主义者则说，当你直接审视觉知本身时，这个问题便自然消解。" } },
    { q: { en: "Are mystical experiences evidence of something beyond the brain?", zh: "神秘体验是否证明存在超越大脑的东西？" }, a: { en: "Materialists interpret them as unusual brain states; dualists and religious thinkers see them as genuine contact with transcendent reality. The experiences themselves are real and often transformative — what they reveal about ultimate reality remains contested.", zh: "唯物主义者将其解释为异常的大脑状态；二元论者与宗教思想家则视之为与超验实在的真实接触。这些体验本身是真实的，且往往具有深刻的转化力量——但它们究竟揭示了怎样的终极实在，仍存在争议。" } },
  ],
  viz: "cards",
  vizTitle: { en: "The Landscape of Consciousness", zh: "意识版图" },
  accent: "#5fd6c4",
};
export default sec;
